version: '3.9'

services:
  trainer:
    image: nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04
    container_name: xerion_trainer
    runtime: nvidia
    volumes:
      - xerion_code:/app # Kod projektu
      - xerion_training_data:/data # Dane treningowe
    working_dir: /app
    command: ["python3", "train_model.py"] # Komenda startowa dla trenowania
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  xerion_code:
    name: xerion_code_volume
  xerion_training_data:
    name: xerion_training_volume
