<?
echo "
<center>
<span class=\"nag2b\">
<b>Informacje o Firmie</b>
</span>
</center>
<br>
<br>";
echo "<center>";
echo "<table width=\"500\" cellpadding=\"0\" cellspacing=\"0\" frame border=\"0\">";

echo "<tr align = \"left\">";
echo "<td>";
echo "
<span class=\"polecam\">

Firma <B>A.Z. GWARANCJA</B> po¶rednicz±ca w obrocie nieruchomo¶ciami powsta³a w 1999 roku. Nasze sukcesy osi±gamy dziêki kompleksowej i profesjonalnej obs³udze, która zdobywa zaufanie coraz wiêkszej liczby klientów.<br>
Dziêki  do¶wiadczeniu i wszechstronnej znajomo¶ci rynku nieruchomo¶ci, nasza nowoczesna, sprawna i dynamiczna firma jest gotowa do wspó³pracy z powa¿nymi kontrahentami, pragn±cymi zaanga¿owaæ siê w ten segment rynku finansowego.<br>
Decyduj±c siê na skorzystanie z naszych us³ug lokuj± Pañstwo swoje zaufanie w pewn± 
i profesjonaln± firmê, której w³a¶cicielem jest:
<ul type = \"1\">
<li>Cz³onek Opolskiego Stowarzyszenia Profesjonalnych Po¶redników Rynku Nieruchomo¶ci;
<li>Cz³onek Polskiej Federacji Rynku Nieruchomo¶ci;
<li>Cz³onek-za³o¿yciel Powszechnego Towarzystwa Ekspertów i Doradców Rynku Nieruchomo¶ci.
</ul>
<b>Zapraszamy do wspó³pracy i korzystania z us³ug A.Z. GWARANCJA.</b>
<br><br>
";

echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursz1&w=400&h=300&i=Siedziba Firmy\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurszm1.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"Siedziba Firmy\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>Siedziba Biura<br>Nieruchomo¶ci<br>(zdjêcia z zewn±trz).</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursz2&w=400&h=300&i=Siedziba Firmy\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurszm2.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"Siedziba Firmy\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursw3&w=400&h=300&i=Siedziba Firmy\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurswm3.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"Siedziba Firmy\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>Siedziba Biura<br>Nieruchomo¶ci<br>(zdjêcia wewn±trz).</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursw4&w=400&h=300&i=Siedziba Firmy\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurswm4.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"Siedziba Firmy\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=img/bud1_b&w=400&h=300&i=Filia I Firmy\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"img/bud1.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"Filia I Firmy\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>I Filia Biura<br>Nieruchomo¶ci<br>(zdjêcia z zewn±trz).</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=img/bud2_b&w=400&h=300&i=Filia I Firmy\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"img/bud2.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"Filia I Firmy\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=img/biur1_b&w=400&h=300&i=Filia I Firmy\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"img/biur1.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"Filia I Firmy\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>I Filia Biura<br>Nieruchomo¶ci<br>(zdjêcia wewn±trz).</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=img/biur2_b&w=400&h=300&i=Filia I Firmy\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"img/biur2.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"Filia I Firmy\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";



echo "
<span class=\"polecam\">
Podstawowymi obszarami dzia³alno¶ci <b>A.Z. GWARANCJA</b> s±, w sektorze nieruchomo¶ci:<br><br>
1. obs³uga prawno-finansowa;<br>
2. sprzeda¿ nieruchomo¶ci w systemie kredytowym;<br>
3. inwestycje na w³asny rachunek;<br>
4. doradztwo; <br>
5. po¶rednictwo w transakcjach kupna/sprzeda¿y i wynajmu wszystkich segmentów rynku, w tym mieszkañ, domów, biur, magazynów, sklepów, obiektów zabytkowych, dzia³ek budowlanych, rolnych i rekreacyjnych; <br>
<br>
<B>Atuty firmy A.Z. GWARANCJA:,</b><br><br>
I. Kompleksowo¶æ us³ug -  oferujemy us³ugê po¶rednictwa obejmuj±c±:<br>
1. umo¿liwienie klientowi wyboru interesuj±cego go obiektu z bazy handlowej zawieraj±cej oferty;<br>
2. pe³na dyspozycyjno¶æ pracowników dostosowana do indywidualnych potrzeb klientów;<br>
3. doradztwo prawne i finansowe dostosowane do sytuacji ka¿dego klienta; <br>
4. pomoc w za³atwieniu wszelkich formalno¶ci prawnych, w tym notarialnych.<br><br>
II. Bogata oferta - A.Z. GWARANCJA posiada du¿± ofertê w rejonie woj. Opolskiego; <br>
III. Profesjonalizm - wysoka kultura obs³ugi klienta w po³±czeniu z wiedz± i do¶wiadczeniem pracowników.<br>
III. Reklama i promocja - firma przywi±zuje du¿± wagê do promocji swoich us³ug i ofert, jest zauwa¿alna zarówno w poczytnej prasie lokalnej, na w³asnych tablicach og³oszeniowych jak i w Internecie. Stosowane przez nas ¶rodki przekazu reklamowego uwzglêdniaj± w³a¶ciw± i rzeteln± ekspozycjê nieruchomo¶ci oferowanych.<br>
IV. Logo firmy - firma pozycjonuje swoj± obecno¶æ na rynku posiadaj±c zastrze¿ony znak graficzny, gwarantuj±cy jednoznaczne rozpoznanie nas w¶ród pozosta³ych biur nieruchomo¶ci.<br>
V. Innowacyjno¶æ i otwarto¶æ na nowe pomys³y - techniczne przygotowanie do realizacji umów bezpo¶rednio w siedzibie kontrahenta, wydajny system przep³ywu informacji, przy tym sta³e poszukiwanie ró¿norodnych dróg dalszego rozwoju na dynamicznie rozwijaj±cym siê rynku nieruchomo¶ci .<br><br>

Nasza przysz³o¶æ to nowoczesna, dynamiczna firma:  <b>A.Z. GWARANCJA</b> dzia³aj±ca zarówno na krajowym, jak i miêdzynarodowym rynku, obs³uguj±ca transakcje na rynku nieruchomo¶ci. <br><br>

Podstawa prawna wykonywania dzia³alno¶ci w zakresie po¶rednictwa w obrocie nieruchomo¶ciami:<br><br>
<center><b>Art. 180</b></center>

1. Po¶rednictwo w obrocie nieruchomo¶ciami polega na zawodowym wykonywaniu przez po¶rednika w obrocie nieruchomo¶ciami czynno¶ci zmierzaj±cych do zawarcia przez inne osoby umów:<br><br>
1) nabycia lub zbycia praw do nieruchomo¶ci,<br>
2) nabycia lub zbycia w³asno¶ciowego spó³dzielczego prawa do lokalu mieszkalnego, spó³dzielczego prawa do lokalu u¿ytkowego lub prawa do domu jednorodzinnego w spó³dzielni mieszkaniowej,<br>
3) najmu lub dzier¿awy nieruchomo¶ci albo ich czê¶ci,<br>
4) innych ni¿ okre¶lone w pkt 1-3, maj±cych za przedmiot prawa do nieruchomo¶ci lub ich czê¶ci.<br><br>
1.a. Po¶rednik w obrocie nieruchomo¶ciami mo¿e wykonywaæ opracowania i ekspertyzy oraz doradztwo w zakresie rynku nieruchomo¶ci.<br>
2. Po¶rednik wykonuje czynno¶ci, o których mowa w ust. 1, osobi¶cie lub przy pomocy innych osób wykonuj±cych czynno¶ci pomocnicze i dzia³aj±cych pod jego bezpo¶rednim nadzorem, ponosz±c za ich czynno¶ci odpowiedzialno¶æ zawodow± okre¶lon± w ustawie.<br>
3. Zakres czynno¶ci po¶rednictwa w obrocie nieruchomo¶ciami okre¶la umowa po¶rednictwa. Umowa wymaga formy pisemnej pod rygorem niewa¿no¶ci. W umowie wskazuje siê po¶rednika w obrocie nieruchomo¶ciami odpowiedzialnego zawodowo za jej wykonanie oraz numer jego licencji zawodowej. W umowie zamieszcza siê o¶wiadczenie o posiadanym ubezpieczeniu odpowiedzialno¶ci cywilnej za szkody wyrz±dzone w zwi±zku z wykonywaniem czynno¶ci po¶rednictwa w obrocie nieruchomo¶ciami.<br>
3a. Umowa po¶rednictwa mo¿e byæ zawarta z zastrze¿eniem wy³±czno¶ci na rzecz po¶rednika lub przedsiêbiorcy. Art. 550 Kodeksu cywilnego stosuje siê odpowiednio.<br>
4. Przez umowê po¶rednictwa po¶rednik lub przedsiêbiorca, o którym mowa w art. 179 ust. 3, zobowi±zuje siê do dokonywania dla zamawiaj±cego czynno¶ci zmierzaj±cych do zawarcia umów, wymienionych w ust. 1, a zamawiaj±cy zobowi±zuje siê do zap³aty po¶rednikowi lub przedsiêbiorcy wynagrodzenia.<br>
5. Sposób ustalenia lub wysoko¶æ wynagrodzenia za czynno¶ci po¶rednictwa w obrocie nieruchomo¶ciami okre¶la umowa po¶rednictwa. W razie nieokre¶lenia wynagrodzenia w umowie, przys³uguje wynagrodzenie zwyczajowo przyjête w danych stosunkach.<br>
6. Czynno¶ci po¶rednictwa w obrocie nieruchomo¶ciami mog± byæ wykonywane w stosunku do wszelkich nieruchomo¶ci, a tak¿e na rzecz wszystkich osób fizycznych i prawnych oraz jednostek organizacyjnych nie posiadaj±cych osobowo¶ci prawnej.<br>
7. Po¶rednik w obrocie nieruchomo¶ciami wykonuje zawód:<br><br>
1) prowadz±c jako przedsiêbiorca dzia³alno¶æ w zakresie po¶rednictwa w obrocie nieruchomo¶ciami albo<br>
2) w ramach stosunku pracy lub umowy cywilnoprawnej u przedsiêbiorcy prowadz±cego dzia³alno¶æ w zakresie po¶rednictwa w obrocie nieruchomo¶ciami.<br><br>
8. Po¶rednik w obrocie nieruchomo¶ciami nie mo¿e ³±czyæ wykonywania zawodu w formach wymienionych w ust. 7.<br>

<br>
<br>
</span>";
echo "</td>";
echo "</tr>";
echo "</table>";
echo "</center>";
?>
