<?
echo "
<center>
<span class=\"nag2b\">
<b>KONTAKT</b>
</span>
</center>
<br><br><br>
<table align=\"center\" width=\"500\">
<tr>
<td align=\"left\" width=\"200\">
<span class=\"polecam\">
<center>
<b>OPOLSKIE BIURO NIERUCHOMO¦CI<br>
A.Z.GWARANCJA<br><br></b>
</center>
<b>SIEDZIBA</b>
<br><br>
ul. Szarych Szeregów 34 d, 45-285 OPOLE<br>
Czynne: pn. - pt. 10.00 - 18.00<br>
tel./fax (0 77) 402-75-20, tel.kom. 0602-531-334<br>
<br>
<b>FILIA I</b>
<br><br>
ul. Bytnara Rudego 13, 45-284 OPOLE<br>
Czynne: pn. - pt. 10.00 - 18.00<br>
tel./fax (0 77) 458-00-94, tel.kom. 0602-531-334<br>
<br>
<br>
Poczta: <a href=\"mailto:azgwarancja@azg.pl\">azgwarancja@azg.pl</a><br>
Adres www: <a href=\"http://www.azg.pl\">www.azg.pl</a>
</span>
</td>
<td width=\"300\" valign=\"top\">
<a href=\"image.php?p=info/mapab&w=600&h=400&i=Mapa\" onclick=\"NewWindow(this.href,'name','620','420','no');return false;\">
	<img src=\"info/mapam.jpg\" width=\"300\" height=\"200\" border=\"0\" alt=\"Mapa Lokalizacyjna\"></a><br><center><span class=\"info\">
	<a href=\"image.php?p=info/mapab&w=600&h=400&i=Mapa\" onclick=\"NewWindow(this.href,'name','620','420','no');return false;\">
	Kliknij, aby powiêkszyæ<br>mapê lokalizacyjn± firmy.</center></a>
</span>
</td>
</tr>
</table>
";
?>