insert into gmina (id_powiat, nazwa) values (355, 'Boles³awiec');
insert into gmina (id_powiat, nazwa) values (355, 'Gromadka');
insert into gmina (id_powiat, nazwa) values (355, 'Nowogrodziec');
insert into gmina (id_powiat, nazwa) values (355, 'Osiecznica');
insert into gmina (id_powiat, nazwa) values (355, 'Warta Boles³awiecka');
insert into gmina (id_powiat, nazwa) values (356, 'Bielawa');
insert into gmina (id_powiat, nazwa) values (356, 'Dzier¿oniów');
insert into gmina (id_powiat, nazwa) values (356, '£agiewniki');
insert into gmina (id_powiat, nazwa) values (356, 'Niemcza');
insert into gmina (id_powiat, nazwa) values (356, 'Pieszyce');
insert into gmina (id_powiat, nazwa) values (356, 'Pi³awa Górna');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Boles³awice');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Boles³awiec');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Bo¿ejowice');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Brze¼nik');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Buczek');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Cho¶ciszowice');
insert into miejscowosc (id_gmina, nazwa) values (1, 'D±browa Boles³awiecka');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Dobra');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Golnice');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Koz³ów');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Kraszowice');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Kra¶nik Dolny');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Kra¶nik Górny');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Krêpnica');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Kruszyn');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Lipiany');
insert into miejscowosc (id_gmina, nazwa) values (1, '£aziska');
insert into miejscowosc (id_gmina, nazwa) values (1, '£±ka');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Mierzwin');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Nowa');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Nowa Wie¶');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Nowe Jaroszowice');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Ocice');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Otok');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Parkoszów');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Pstr±¿e');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Rakowice');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Stara Oleszna');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Stare Jaroszowice');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Suszki');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Trzebieñ');
insert into miejscowosc (id_gmina, nazwa) values (1, 'Trzebieñ Ma³y');
insert into miejscowosc (id_gmina, nazwa) values (1, '¯eliszów');
insert into gmina (id_powiat, nazwa) values (357, 'G³ogów');
insert into gmina (id_powiat, nazwa) values (357, 'Jerzmanowa');
insert into gmina (id_powiat, nazwa) values (357, 'Kotla');
insert into gmina (id_powiat, nazwa) values (357, 'Pêc³aw');
insert into gmina (id_powiat, nazwa) values (357, '¯ukowice');
