<?
echo "
<center>
<span class=\"nag2b\">
<b>&nbsp;CERTIFICATES</b>
</span>
</center>
<br>
<br>
<center>";


echo "<table>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=../img/licenandy_b&w=300&h=406&i=Certyificates of License\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/licenandy.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Œwiadectwo Licencji\"></a>";
echo "</td>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=../img/swiadectwo_b&w=300&h=406&i=Certyificates of License\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/swiadectwo.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Certyificates of License\"></a>";
echo "</td>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=../img/licenida_b&w=300&h=406&i=Certyificates of License\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/licenida.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Œwiadectwo Licencji\"></a>";
echo "</td>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=info/licenar_b&w=300&h=406&i=Certyificates of License\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"info/licenar.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Œwiadectwo Licencji\"></a>";
echo "</td>";

echo "</tr>";
echo "</table>";

echo "<br>";

echo "<table>";

echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=info/licenma_b&w=300&h=406&i=Certyificates of License\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"info/licenma.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Œwiadectwo Licencji\"></a>";
echo "</td>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=../img/certhom_b&w=320&h=460&i=Certyificates of HOMO\" onclick=\"NewWindow(this.href,'name','340','480','no');return false;\">";
	echo "<img src=\"../img/certhom.jpg\" width=\"110\" height=\"135\" border=\"0\" alt=\"Certyificates of HOMO\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/kongr_b&w=300&h=406&i=Certyificates of Congress\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/kongr.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Certyificates of Congress\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/dypuzn_b&w=300&h=406&i=Diploma\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/dypuzn.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Diploma\"></a>";
echo "</td></tr>";
echo "</table>";


echo "<br>";

echo "<table>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=info/kongresx_b&w=300&h=406&i=Congress\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"info/kongresx.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Congress\"></a>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=../img/ean0_b&w=320&h=460&i=EAN\" onclick=\"NewWindow(this.href,'name','340','480','no');return false;\">";
	echo "<img src=\"../img/ean0.jpg\" width=\"110\" height=\"135\" border=\"0\" alt=\"EAN\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/kongres_b&w=300&h=406&i=Congress\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/kongres.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Congress\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/ubezpieczenie_b&w=300&h=406&i=Certyificates of HDI\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/ubezpieczenie.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Certyificates of HDI\"></a>";
echo "</td></tr>";
echo "</table>";


echo "<br>";
echo "<table>";
echo"<tr align=\"center\">";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/ean1_b&w=300&h=406&i=EAN -  I course\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/ean1.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - I course\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/ean2_b&w=300&h=406&i=EAN - II course\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/ean2.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - II course\"></a>";
echo "</td>";

echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/ean3_b&w=300&h=406&i=EAN - III course\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/ean3.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - III course\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/ean4_b&w=300&h=406&i=EAN - IV course\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/ean4.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - IV course\"></a>";
echo "</td></tr>";
echo "</table>";
echo "</center>";
?>
