<?
echo "
<center>
<span class=\"nag2b\">
<b>Company info</b>
</span>
</center>
<br>
<br>";
echo "<center>";
echo "<table width=\"500\" cellpadding=\"0\" cellspacing=\"0\" frame border=\"0\">";

echo "<tr align = \"left\">";
echo "<td>";
echo "
<span class=\"polecam\">

The real estate agency <b>A.Z. GWARANCJA</b> was established in 1999. Our firm is always guaranteeing the very highest standards of service and gaining an enviable reputation for results.<br>
Drawing on our experience and knowledge, contacts and commitment, we will endeavour to identify suitable property that fits your requirements.<br>
Deciding for our services you're choosing dynamic, efficient and professional firm which will provide you:
<ul type=\"1\">
<li>legal-financial service;
<li>sale of the property in the credit system;
<li>investments on one's own account;
<li>consulting;
<li>mediation in transactions of purchase/sale and renting of all segments of the market - houses, offices, magazines, shops, antique objects, agricultural and recreational, building plots;
</ul>
</span>";


echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursz1&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurszm1.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>The Firm of Real Estate<br>(pictures - outside).</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursz2&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurszm2.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursw3&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurswm3.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>The Firm of Real Estate<br>(pictures - inside).</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursw4&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurswm4.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";


echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/bud1_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/bud1.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>I Real Estate Agency<br>(pictures - outside).</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/bud2_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/bud2.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/biur1_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/biur1.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>I Real Estate Agency<br>(pictures - inside).</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/biur2_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/biur2.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";


echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/bud3_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/bud3.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>II Real Estate Agency<br>(pictures - outside).</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/bud4_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/bud4.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/biur3_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/biur3.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>II Real Estate Agency<br>(pictures - inside).</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/biur4_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/biur4.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "
<span class=\"polecam\">
Advantages of cooperation with A.Z GWARANCJA:
<br>
I. complexity of services - we are offering the service of the mediation including:
<ul type=\"1\">
<li>enabling the customer the choice of the object interesting him from the commercial offers base;
<li>workers' full availability adapted to individual needs our customers;
<li>legal and financial consulting adapted to every customer's situation;
<li>help in taking care of every legal formalities, in it notarized.
</ul>
Having found you the property we will use our experience, expertise and local knowledge to negotiate the reasonable price for you!
<br>
Once the price has been negotiated we will ensure that the transaction proceeds smoothly from the beginning to legal completion.
<br>
We will liaise with solicitors, banks and surveyors on you behalf.
<br>
<br>

</span>";
echo "</td>";
echo "</tr>";
echo "</table>";
echo "</center>";
?>
