<?
echo "
<center>
<span class=\"nag2b\">
<b>Kinds of sale</b>
</span>
</center>
<br>
<br>";
echo "<center>";
echo "<table width=\"500\" cellpadding=\"0\" cellspacing=\"0\" frame border=\"0\">";

echo "<tr align = \"left\">";
echo "<td>";
echo "
<span class=\"polecam\">

We are taking cooperation on principles of the open agreement and the agreement with the clause of exclusive rights.<br><br>

<b>WHAT IS THE IDEA OF EXCLUSIVE RIGHTS?</b><br><br>
Agreements with the clause of exclusive rights are the best form of sale your property. It is basic method of mediators' activity on the western market which is also  excellently proved in Polish realities.<br><br>

<b>1. SAVING TIME AND MONEY.</b><br><br>
The agreement is obliging the mediator to numbers of actions in the sphere of the promotion and the advertisement, in it of entrusting the offer to other agencies (what is corresponding to the application the offer for a few dozen of offices in the whole province). The seller who's undertaking this work by himself wasting time for making an appointment with mediators, answering the same questions, analyzing agreements, showing the object. This action, certainly time-consuming, it could be also quite expensive in case when the offered property is lying apart from the actual place of the seller's residence.<br><br>

<b>2. INCREASE IN EFFECTIVENESS.</b><br><br>
Having the signed agreement for exclusive rights the office is capable of leading the wide sale policy. Agency is able to give more detailed information about property, photos of the building from outside to the selecting group of potential buyers. To attach their interest in notices in press or in the Internet offer. Such method of presentation bringing even 40 % increase in effectiveness. The office will expend its money having guaranteed payment in case of sale.<br><br>

<b>3. PROFITS.</b><br><br>
Possibility of the wide advertisement plus cooperation with the other agencies is permitting to obtain the good market price. This price will be paid by the client selected from the big group of potential buyers, because the offer will be full-fitting to his expectations.<br><br>

<br>
</span>";
echo "</td>";
echo "</tr>";
echo "</table>";
echo "</center>";
?>
