<?
echo "
<center>
<span class=\"nag2b\">
<b>Information for the customers</b>
</span>
</center>
<br>
<br>";
echo "<center>";
echo "<table width=\"500\" cellpadding=\"0\" cellspacing=\"0\" frame border=\"0\">";

echo "<tr align = \"left\">";
echo "<td>";
echo "
<span class=\"polecam\">
If you want to choose professional real estate agency you have to pay attention on the things numbered below: 
<ul type=\"1\">
<li>Check if the office has agent with the licence which is necessary to work on real estate market in Poland.
<li>Is the office insured against the civil liability?
<li>How long the firm working on the market?
<li>Is the chosen office one of the members of regional associations organized into Polish Real Estate Federation? <br><br>
The mission of the Polish Real Estate Federation is to ensure the enhancement of the Polish real estate market, namely advancement in the direction of excellent services being provided by its members, building correct information systems for the public and government, and ensuring that all property professionals are united for the good of the market.
<br><br>
<li> Check if the office is present on local press and Internet in order to be able to promote and advertise you property in effective way?
</ul>
The choice of the adequate real estate agency is the guarantee of cooperation with the professional partner which results in measurable success.
<br>
</span>";
echo "</td>";
echo "</tr>";
echo "</table>";
echo "</center>";
?>
