<?
echo "
<center>
<span class=\"nag2b\">
<b>CONTACT</b>
</span>
</center>
<br><br><br>


<table align=\"center\" width=\"500\">
<tr>
<td align=\"left\" width=\"200\">
<span class=\"polecam\">
<center>
<b>REAL ESTATE AGENCY IN OPOLE<br>
A.Z.GWARANCJA<br><br></b>
</center>
<b>THE OFFICE</b>
<br><br>
Open: mon. - fri. 10.00 - 18.00, sat. 10.00 - 14.00<br>
tel./fax (0 77) 458-00-94, mobile phone: 0602-531-334<br>
<br>
<b>AGENCY I</b>
<br><br>
st. Bytnara Rudego 13, 45-284 OPOLE<br>
Open: mon. - fri. 10.00 - 18.00, sat. 10.00 - 14.00<br>
tel./fax (0 77) 458-00-94, mobile phone: 0602-531-334<br>
<br>
<b>AGENCY II</b>
<br><br>
Building of Housing Association ZWM<br>
I floor, room 118A<br>
st. Sosnkowskiego 40-42, 45-284 OPOLE<br>
Open: mon. - fri. 10.00 - 15.00<br>
tel./fax (0 77) 457-96-99<br><br>
E-mail: <a href=\"mailto:azgwarancja@azg.pl\">azgwarancja@azg.pl</a><br>
WWW: <a href=\"http://www.azg.pl\">www.azg.pl</a>
</span>
</td>
<td width=\"300\" valign=\"top\">
<a href=\"image.php?p=info/mapab&w=600&h=400&i=Mapa\" onclick=\"NewWindow(this.href,'name','620','420','no');return false;\">
	<img src=\"info/mapam.jpg\" width=\"300\" height=\"200\" border=\"0\" alt=\"Mapa Lokalizacyjna\"></a><br><center><span class=\"info\">
	<a href=\"image.php?p=info/mapab&w=600&h=400&i=Mapa\" onclick=\"NewWindow(this.href,'name','620','420','no');return false;\">Click for enlarge the Picture.</center></a>
</span>
</td>
</tr>
</table>
";
?>