<?
echo "
<center>
<span class=\"nag2b\">
<b>&nbsp;ZERTIFIKATEN</b>
</span>
</center>
<br>
<br>
<center>";
echo "<table>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=../img/licenandy_b&w=300&h=406&i=Zertifikat 1\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/licenandy.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Zertifikat 1\"></a>";
echo "</td>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=../img/swiadectwo_b&w=300&h=406&i=Zertifikat 2\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/swiadectwo.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Zertifikat 2\"></a>";
echo "</td>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=../img/licenida_b&w=300&h=406&i=Zertifikat 3\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/licenida.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Zertifikat 3\"></a>";
echo "</td>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=info/licenar_b&w=300&h=406&i=Zertifikat 4\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"info/licenar.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Zertifikat 4\"></a>";
echo "</td>";

echo "</tr>";
echo "</table>";

echo "<br>";

echo "<table>";

echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=info/licenma_b&w=300&h=406&i=Zertifikat 5\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"info/licenma.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Zertifikat 5\"></a>";
echo "</td>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=../img/certhom_b&w=320&h=460&i=Zertifikat - HOMO\" onclick=\"NewWindow(this.href,'name','340','480','no');return false;\">";
	echo "<img src=\"../img/certhom.jpg\" width=\"110\" height=\"135\" border=\"0\" alt=\"Zertifikat - HOMO\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/kongr_b&w=300&h=406&i=Zertifikat den Kongress\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/kongr.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Zertifikat den Kongress\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/dypuzn_b&w=300&h=406&i=Diplom\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/dypuzn.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Diplom \"></a>";
echo "</td></tr>";
echo "</table>";


echo "<br>";

echo "<table>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=info/kongresx_b&w=300&h=406&i=Kongress\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"info/kongresx.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Kongress\"></a>";
echo "</td>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=../img/ean0_b&w=320&h=460&i=EAN\" onclick=\"NewWindow(this.href,'name','340','480','no');return false;\">";
	echo "<img src=\"../img/ean0.jpg\" width=\"110\" height=\"135\" border=\"0\" alt=\"Œwiadectwo Licencji\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/kongres_b&w=300&h=406&i=Kongress\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/kongres.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Kongress\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/ubezpieczenie_b&w=300&h=406&i=Zertifikat HDI\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/ubezpieczenie.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Zertifikat HDI\"></a>";
echo "</td></tr>";
echo "</table>";

echo "<br>";

echo "<table>";
echo"<tr align=\"center\">";
echo "<td valign=\"center\">";
	echo "<a href=\"../image.php?p=../img/pfrn_b&w=600&h=422&i=Teilnehmer PFRN\" onclick=\"NewWindow(this.href,'name','620','448','no');return false;\">";
	echo "<img src=\"../img/pfrn.jpg\" width=\"150\" height=\"116\" border=\"0\" alt=\"Teilnehmer PFRN\"></a>";
echo "</td>";

echo "<td valign=\"center\">";
	echo "<a href=\"../image.php?p=../img/ceosp_b&w=600&h=422&i=Teilnehmer OSPPRN\" onclick=\"NewWindow(this.href,'name','620','448','no');return false;\">";
	echo "<img src=\"../img/ceosp.jpg\" width=\"150\" height=\"116\" border=\"0\" alt=\"Teilnehmer OSPPRN\"></a>";
echo "</td></tr>";

echo "<br>";

echo "<table>";
echo"<tr align=\"center\">";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/ean1_b&w=300&h=406&i=EAN -  I\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/ean1.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - I\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/ean2_b&w=300&h=406&i=EAN - II\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/ean2.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - II\"></a>";
echo "</td>";

echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/ean3_b&w=300&h=406&i=EAN - III\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/ean3.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - III\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=../img/ean4_b&w=300&h=406&i=EAN - IV\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"../img/ean4.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - IV\"></a>";
echo "</td></tr>";
echo "</table>";
echo "</center>";
?>
