<?
echo "
<center>
<span class=\"nag2b\">
<b>MITTEILUNGEN ÜBER DIE FIRMA A.Z.GWARANCJA</b>
</span>
</center>
<br>
<br>";
echo "<center>";
echo "<table width=\"500\" cellpadding=\"0\" cellspacing=\"0\" frame border=\"0\">";

echo "<tr align = \"left\">";
echo "<td>";
echo "
<span class=\"polecam\">
Die Firma <b>A.Z. GWARANCJA</b>vermittelt im Handel der Immobilien. Sie entstand im Jahre 1999. Dank der komplexen und professionellen Bedingung gewinnen wir immer mehr Kunden und haben immer mehr Erfolge.<br>
Aufgrund unserer Erfahrungen und allseitiger Immobilienmarktkenntnisse ist unsere moderne, leistungsfähige und dynamische Firma zur Zusammenarbeit mit ehrlichen Vertragspartnern (die sich in diesem Segment des Finanzmarktes arrangieren möchten) bereit.<br>
Entscheiden Sie sich auf das Nutzen unserer Dienstleistungen, bringen Sie Ihr Vertrauen in sichere, professionelle Firma unter, derer Eigentümer zu folgenden Organisationen gehört:
<ul type=\"1\">
<li>Oppelner Gesellschaft professioneller Vermittler des Immobilienmarktes;
<li>Mitglied des polnischen Immobilienmarktbundes;
<li>Mitglied-Gründer der allgemeinen Gesellschaft der Experten und Berater des Immobilienmarktes.
</ul>
<b>Wir laden Sie zur Zusammenarbeit und Nutzung der Dienstleistungen der Firma A.Z.GWARANCJA ein.</b>
</span>";


echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursz1&w=400&h=300&i=STAMMSITZ\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurszm1.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"STAMMSITZ\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>STAMMSITZ.</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursz2&w=400&h=300&i=STAMMSITZ\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurszm2.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"STAMMSITZ\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursw3&w=400&h=300&i=STAMMSITZ\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurswm3.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"STAMMSITZ\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>STAMMSITZ.</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=info/biursw4&w=400&h=300&i=STAMMSITZ\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"info/biurswm4.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"STAMMSITZ\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";



echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/bud1_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/bud1.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>I IMMOBILIENBÜROS.</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/bud2_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/bud2.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/biur1_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/biur1.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>I IMMOBILIENBÜROS.</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/biur2_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/biur2.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";


echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/bud3_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/bud3.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>II ZWEIGSTELLE.</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/bud4_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/bud4.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<table width =516>";
echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/biur3_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/biur3.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";

echo "<td align=\"center\" width=\"144\" >";
echo "<span class=\"polecam\">
<b>II ZWEIGSTELLE.</b>
</span>";
echo "</td>";

echo "<td align=\"center\" width=\"186\" >";
	echo "<a href=\"image.php?p=../img/biur4_b&w=400&h=300&i=The Firm\" onclick=\"NewWindow(this.href,'name','420','320','no');return false;\">";
	echo "<img src=\"../img/biur4.jpg\" width=\"180\" height=\"135\" border=\"0\" alt=\"The Firm\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "
<span class=\"polecam\">
Im Immobiliengebiet stellen wir für Sie folgende Dienstleistungen:
<br>
<ul type=\"1\">
<li>Gesetzlich-finanzielle Bedingung;
<li>Verkauf von Immobilien im Kreditsystem;
<li>Investitionen auf eigene Rechnung;
<li>Beratung;
<li>Vermittlung in den Transaktionen von Kauf und Verkauf sowie in Mieten aller Marktsegmente der Immobilien wie Wohnungen, Häuser, Büros, Lager, Läden, Baudenkmäler und verschiedener Arten von Grundstücken;
</ul>
Vorteile der Firma A.Z.GWARANCJA
<br>
<ul type=\"1\">
<li>Wir stellen Ihnen komplexen Dienstleistungsbereich zur Verfügung. Er fasst folgende Dienste um:
<ul type=\"1\">
<li>ermöglicht dem Kunden eine Objektauswahl aus dem, ihn interessierenden Angebot;
<li>volle Verfügbarkeit unserer Mitarbeiter, die zu den individuellen Bedürfnissen der Kunden angepasst sind;
<li>gesetzliche und finanzielle Beratung die an individuelle Bedürfnisse der Kunden angepasst sind;
<li>Hilfe bei der Erledigung der gesetzlichen Formalitäten, darunter bei den notariellen Urkunden.
</ul>
<li>A.Z.GWARANCJA besitzt in ihrem Angebot sehr viele Objekte in der Oppelner Region;
<li>Professionalität und kulturelle Bedienung der Kunden in der Verbindung mit dem Wissen und der Erfahrung der Mitarbeiter der Firma.
<li>Werbung und Förderung - die Firma achtet auf die Förderung ihrer Dienstleistungen und Angebote, sie ist in den lokalen Zeitungen bemerkbar, hat eigene Werbungstafel sowie Webseite. Die durch uns angewendeten Werbungsmittel berücksichtigen richtige und ehrliche Präsentation der angebotenen Immobilien.
<li>Firmenzeichen - die Firma ist durch ihr vorbehaltenes Firmenzeichen erkennbar. Das Firmenzeichen hebt uns von anderen Immobilienfirmen hervor.
<li>Innovation und Öffentlichkeit auf neue Ideen - technische Vorbereitung zur Verwirklichung der Verträge unmittelbar im Sitz des Vertragspartners, leistungsfähiges System des Informationsflusses, dabei ständiges Suchen verschiedener Wege der Weiterentwicklung auf dem sich dynamisch entwickelten Immobilienmarkt.
</ul>
Unsere Zukunft heißt moderne, dynamische Firma A.Z.GWARANCJA, die nicht nur auf dem Landesmarkt sondern auch auf dem internationalen Markt wirken wird.
<br>
<br>
Rechtsgrundlage für die Ausführung der Tätigkeit im Bereich des Immobilienverkehrs:
<br>
<br>
Artikel 180
<br>
<br>
<ul type=\"1\">
<li>Vermittlung in dem Immobilienverkehr beruht auf der beruflichen Ausführung durch den Vermittler bestimmter Tätigkeiten, die zur Schließen eines Vertrages zwischen verschiedenen Personen führen. Diese Verträge fassen folgende Formen um:
<ul type=\"1\">
<li>Erwerb oder Absatz des Rechts zu Immobilien,
<li>Erwerb oder Absatz des Rechts zur Genossenschaftseigentumswohnung, Genossenschaftsrechtes zum Nutzlokal oder des Rechts zum Einfamilienhaus in der Wohnungsbaugenossenschaft,
<li>Miete oder Pacht der Immobilien oder ihrer Teile,
<li>Andere als in den obigen Punkten genannter Gegenstände, die gesetzlich als Immobilien oder ihre Teile zu verstehen sind.
</ul>
<li>Vermittler im Immobilienverkehr kann Bearbeitungen und Gutachten sowie Beratung im Immobilienbereich ausüben.
<li>Vermittler übt die im Absatz 1 genannten Tätigkeiten persönlich aus oder mit Hilfe von anderen Personen, die Hilfstätigkeiten ausüben und unter seiner Aufsicht wirken. Der Vermittler trägt die Verantwortung für die Tätigkeit des Hilfspersonals gemäß des Gesetzes.
<li>Vermittlungstätigkeitsbereich im Immobilienverkehr bestimmt der Vermittlungsvertrag. Der Vertrag erfordert eine schriftliche Form. Mündliche Vereinbarungen sind nicht verbindlich. Im Vertrag nennt man den Vermittler im Immobilienverkehr, der für die Kraftsetzung des Vertrags beruflich verantwortlich ist. Seine Lizenznummer steht auch im Vertrag sowie die Erklärung über Haftpflichtversicherung für eventuelle Schäden, die während der Transaktion des Immobilienverkehrs entstehen können.
<li>Vermittlungsvertrag kann mit dem Vorbehalt der Ausschließlichkeit zugunsten des Vermittlers oder Unternehmers abgeschlossen werden. Artikel 550 der Zivilordnung wendet man entsprechend an
<li>Gemäß des Vermittlungsvertrags verpflichtet sich der Vermittler oder Unternehmer, über den man im Artikel 179 Absatz 3 spricht, zum Vollbringen für den Besteller der Tätigkeiten die zum Abschließen der Verträge führen und die im Absatz 1 genannt sind. Der Besteller verpflichtet sich zur Bezahlung des Gehaltes dem Vermittler oder dem Unternehmer.
<li>Bestimmungsweise und Lohnhöhe für die Vermittlung im Immobilienverkehr bestimmt der Vermittlungsvertrag. Im Fall der Nichtbestimmung des Lohnes im Vertragsrahmen, steht dem Vermittler gewohnheitsmäßig angenommener Lohn zu.
<li>Vermittlungstätigkeiten im Immobilienverkehr können in Verhältnis zu allen Arten von Immobilien und zugunsten aller natürlichen und juristischen Personen sowie Organisationseinheiten die keine juristische Persönlichkeit besitzen ausüben werden.
<li>Vermittler im Immobilienverkehr übt den Beruf aus:
<ul type=\"1\">
<li>durch die Tätigkeitsführung als Unternehmer im Bereich der Vermittlung im Immobi-lienverkehr oder,
<li>im Rahmen des Arbeitsverhältnisses oder des Privatjuristischenabkommens mit dem Unternehmer, der die Aktivität im Bereich des Immobilienverkehrs führt.
</ul>
<li>Vermittler des Immobilienverkehrs kann nicht gleichzeitig in beiden im Absatz 7 genannter Formen wirken.
</ul>

</span>";
echo "</td>";
echo "</tr>";
echo "</table>";
echo "</center>";
?>
