<?
echo "
<center>
<span class=\"nag2b\">
<b>Informationen für die Kunden</b>
</span>
</center>
<br>
<br>";
echo "<center>";
echo "<table width=\"500\" cellpadding=\"0\" cellspacing=\"0\" frame border=\"0\">";

echo "<tr align = \"left\">";
echo "<td>";
echo "
<span class=\"polecam\">
Bei der Auswahl des Immobilienbüros mit dem Sie zusammenarbeiten möchten sollen Sie auf folgende Aspekte achten: 
<ul type=\"1\">
<li>Hat das Büro einen Lizenzvermittler im Immobilienverkehr ?
<li>Besitzt das Büro die Haftpflichtversicherung ?
<li>Seit wann ist das Büro auf dem Markt ?
<li>Ist das Büro das Mitglied einer Genossenschaft oder eines Bundes die die pro-fessionellen Immobilienvermittler vereinigen ? 
<li>Ist das Büro in der lokalen Presse oder im Internet anwesend um Ihre Angebote effektiv werben und fördern ?
</ul>
Die Auswahl eines entsprechenden Vermittlungsbüros im Immobilienverkehr gewährleistet Ihnen eine gute Zusammenarbeit mit einem entsprechenden und professionellen Partner. Nur mit einem solchem Vermittler verkaufen Sie Ihre Immobilien erfolgreich.
<br>
</span>";
echo "</td>";
echo "</tr>";
echo "</table>";
echo "</center>";
?>
