<?
echo "
<center>
<span class=\"nag2b\">
<b>KONTAKT</b>
</span>
</center>
<br><br><br>
<table align=\"center\" width=\"500\">
<tr>
<td align=\"left\" width=\"200\">
<span class=\"polecam\">
<center>
<b>IMMOBILIEN A.Z.GWARANCJA IN OPPELN<br>
A.Z.GWARANCJA<br><br></b>
</center>
<b>STAMMSITZ</b>
<br><br>
Str. Bytnara Rudego 13,<br>
Stadt OPOLE 45-284<br>
Von Mo. bis Fr. 10.00 - 18.00 Uhr, Sa. 10.00 - 14.00<br>
tel./fax +48 77 458 00 94, mobiles tel.: 0602-531-334<br><br><br>

<b>FILIALE NR 1</b>
<br><br>
Str. Bytnara Rudego 13,<br>
Stadt OPOLE 45-284<br>
Von Mo. bis Fr. 10.00 - 18.00 Uhr, Sa. 10.00 - 14.00<br>
tel./fax +48 77 458 00 94, mobiles tel.: 0602-531-334<br><br><br>

<b>FILIALE NR 2</b><br><br>
Gebäude der Wohngesellschaft ZWM<br>
I Etage, Raum. 118A<br>
Str. Sosnkowskiego 40-42,
Stadt OPOLE 45-284<br>
Von Mo. bis Fr. 8.00 - 15.00 Uhr, Di. 8.00 - 17.00<br>
tel./fax +48 77 457 96 99<br><br><br>
E-mail: <a href=\"mailto:azgwarancja@azg.pl\">azgwarancja@azg.pl</a><br>
WWW: <a href=\"http://www.azg.pl\">www.azg.pl</a>
</span>
</td>
<td width=\"300\" valign=\"top\">
<a href=\"image.php?p=info/mapab&w=600&h=400&i=Mapa\" onclick=\"NewWindow(this.href,'name','620','420','no');return false;\">
	<img src=\"info/mapam.jpg\" width=\"300\" height=\"200\" border=\"0\" alt=\"Lokalisation\"></a><br><center><span class=\"info\">
	<a href=\"image.php?p=info/mapab&w=600&h=400&i=Map\" onclick=\"NewWindow(this.href,'name','620','420','no');return false;\">
Klicken Sie um die Lokalisationskarte der Firma zu vergrößern.</center></a>
</span>
</td>
</tr>
</table>
";
?>
