<?

if (!isset($action)) {
$action = 'sprzedazm';
}

if ($action == 'kalku') {

 include "info/kalkulator.inc"; 

}

if ($action == 'kredyty') {

 include "info/kredyty.inc"; 

}

if ($action == 'firma') {

 include "info/firma.inc"; 

}

if ($action == 'kontakt') {

 include "info/kontakt.inc"; 

}

if ($action == 'certy') {

 include "info/certy.inc"; 

}
if ($action == 'oblicz') {

 include "info/kalkulator.inc"; 

}

if ($action == 'info') {

 include "info/info.inc"; 

}

if ($action == 'formy') {

 include "info/formy.inc"; 

}
if ($action == 'sprzedazm') {

 include "sprzedaz/sprzedazm.inc"; 

}

if ($action == 'sprzedazmzd') {

 include "sprzedaz/sprzedazm.inc"; 

}

if ($action == 'sprzedazmt') {

 include "sprzedaz/sprzedazm.inc"; 

}


if ($action == 'sprzedazd') {

 include "sprzedaz/sprzedazd.inc"; 

}
if ($action == 'sprzedazdzd') {

 include "sprzedaz/sprzedazd.inc"; 

}

if ($action == 'sprzedazdt') {

 include "sprzedaz/sprzedazd.inc"; 

}

if ($action == 'sprzedazl') {

 include "sprzedaz/sprzedazl.inc"; 

}
if ($action == 'sprzedazlzd') {

 include "sprzedaz/sprzedazl.inc"; 

}


if ($action == 'sprzedazo') {

 include "sprzedaz/sprzedazo.inc"; 

}
if ($action == 'sprzedazozd') {

 include "sprzedaz/sprzedazo.inc"; 

}

if ($action == 'sprzedazdz') {

 include "sprzedaz/sprzedazdz.inc"; 

}
if ($action == 'sprzedazdzzd') {

 include "sprzedaz/sprzedazdz.inc"; 

}

if ($action == 'sprzedazte') {

 include "sprzedaz/sprzedazte.inc"; 

}
if ($action == 'sprzedaztezd') {

 include "sprzedaz/sprzedazte.inc"; 

}


if ($action == 'wynajemm') {

 include "wynajem/wynajemm.inc"; 

}
if ($action == 'wynajemmzd') {

 include "wynajem/wynajemm.inc"; 

}

if ($action == 'wynajemmt') {

 include "wynajem/wynajemm.inc"; 

}


if ($action == 'wynajemd') {

 include "wynajem/wynajemd.inc"; 

}
if ($action == 'wynajemdzd') {

 include "wynajem/wynajemd.inc"; 

}

if ($action == 'wynajemdt') {

 include "wynajem/wynajemd.inc"; 

}

if ($action == 'wynajeml') {

 include "wynajem/wynajeml.inc"; 

}
if ($action == 'wynajemlzd') {

 include "wynajem/wynajeml.inc"; 

}


if ($action == 'wynajemo') {

 include "wynajem/wynajemo.inc"; 

}
if ($action == 'wynajemozd') {

 include "wynajem/wynajemo.inc"; 

}

if ($action == 'wynajemdz') {

 include "wynajem/wynajemdz.inc"; 

}
if ($action == 'wynajemdzzd') {

 include "wynajem/wynajemdz.inc"; 

}

if ($action == 'wynajemte') {

 include "wynajem/wynajemte.inc"; 

}
if ($action == 'wynajemtezd') {

 include "wynajem/wynajemte.inc"; 

}

if ($action == 'zamianam') {

 include "zamiana/zamianam.inc"; 

}
if ($action == 'zamianamzd') {

 include "zamiana/zamianam.inc"; 

}

if ($action == 'zamianad') {

 include "zamiana/zamianad.inc"; 

}
if ($action == 'zamianadzd') {

 include "zamiana/zamianad.inc"; 

}

if ($action == 'kupnom') {

 include "kupno/kupnom.inc"; 

}
if ($action == 'kupnomzd') {

 include "kupno/kupnom.inc"; 

}

if ($action == 'kupnomt') {

 include "kupno/kupnom.inc"; 

}


if ($action == 'kupnod') {

 include "kupno/kupnod.inc"; 

}
if ($action == 'kupnodzd') {

 include "kupno/kupnod.inc"; 

}

if ($action == 'kupnodt') {

 include "kupno/kupnod.inc"; 

}

if ($action == 'kupnol') {

 include "kupno/kupnol.inc"; 

}
if ($action == 'kupnolzd') {

 include "kupno/kupnol.inc"; 

}


if ($action == 'kupnoo') {

 include "kupno/kupnoo.inc"; 

}
if ($action == 'kupnoozd') {

 include "kupno/kupnoo.inc"; 

}

if ($action == 'kupnodz') {

 include "kupno/kupnodz.inc"; 

}
if ($action == 'kupnodzzd') {

 include "kupno/kupnodz.inc"; 

}

if ($action == 'kupnote') {

 include "kupno/kupnote.inc"; 

}
if ($action == 'kupnotezd') {

 include "kupno/kupnote.inc"; 

}

if ($action == 'dodajsub') {

 include "sub/sub.inc"; 

}

if ($action == 'wprowadzsub') {

 include "sub/sub.inc"; 

}

if ($action == 'dodajform') {

 include "form.inc"; 

}

if ($action == 'emailform') {

 include "form.inc"; 

}

?>