<?
echo "
<center>
<span class=\"nag2b\">
<b>&nbsp;CERTYFIKATY</b>
</span>
</center>
<br>
<br>
<center>";
echo "<table>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=img/licenandy_b&w=300&h=406&i=Œwiadectwo Licencji\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"img/licenandy.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Œwiadectwo Licencji\"></a>";
echo "</td>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=img/swiadectwo_b&w=300&h=406&i=Œwiadectwo Licencji\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"img/swiadectwo.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Œwiadectwo Licencji\"></a>";
echo "</td>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=img/licenida_b&w=300&h=406&i=Œwiadectwo Licencji\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"img/licenida.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Œwiadectwo Licencji\"></a>";
echo "</td>";
echo "</tr>";
echo "</table>";

echo "<br>";

echo "<table>";
echo "<td align=\"center\" >";
	echo "<a href=\"image.php?p=img/ean0_b&w=320&h=460&i=EAN\" onclick=\"NewWindow(this.href,'name','340','480','no');return false;\">";
	echo "<img src=\"img/ean0.jpg\" width=\"110\" height=\"135\" border=\"0\" alt=\"Œwiadectwo Licencji\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=img/kongres_b&w=300&h=406&i=Kongres\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"img/kongres.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Kongres\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=img/wa_b&w=300&h=406&i=Certyfikat Warta\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"img/wa.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"Certyfikat Warta\"></a>";
echo "</td></tr>";
echo "</table>";

echo "<br>";

echo "<table>";
echo"<tr align=\"center\">";
echo "<td valign=\"center\">";
	echo "<a href=\"../image.php?p=img/pfrn_b&w=600&h=422&i=Cz³onek PFRN\" onclick=\"NewWindow(this.href,'name','620','448','no');return false;\">";
	echo "<img src=\"img/pfrn.jpg\" width=\"150\" height=\"116\" border=\"0\" alt=\"Cz³onek PFRN\"></a>";
echo "</td>";

echo "<td valign=\"center\">";
	echo "<a href=\"../image.php?p=img/ceosp_b&w=600&h=422&i=Cz³onek OSPPRN\" onclick=\"NewWindow(this.href,'name','620','448','no');return false;\">";
	echo "<img src=\"img/ceosp.jpg\" width=\"150\" height=\"116\" border=\"0\" alt=\"Cz³onek OSPPRN\"></a>";
echo "</td></tr>";

echo"
</table>
";

echo "<br>";
echo "<table>";
echo"<tr align=\"center\">";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=img/ean1_b&w=300&h=406&i=EAN - cz. I kursu\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"img/ean1.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - cz. I kursu\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=img/ean2_b&w=300&h=406&i=EAN - cz. II kursu\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"img/ean2.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - cz. II kursu\"></a>";
echo "</td>";

echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=img/ean3_b&w=300&h=406&i=EAN - cz. III kursu\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"img/ean3.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - cz. III kursu\"></a>";
echo "</td>";
echo "<td valign=\"center\">";
	echo "<a href=\"image.php?p=img/ean4_b&w=300&h=406&i=EAN - cz. IV kursu\" onclick=\"NewWindow(this.href,'name','320','426','no');return false;\">";
	echo "<img src=\"img/ean4.jpg\" width=\"100\" height=\"135\" border=\"0\" alt=\"EAN - cz. IV kursu\"></a>";
echo "</td></tr>";
echo "</table>";
echo "</center>";
?>
