<?
echo "
<center>
<span class=\"nag2b\">
<b>Formy Sprzeda¿y</b>
</span>
</center>
<br>
<br>";
echo "<center>";
echo "<table width=\"500\" cellpadding=\"0\" cellspacing=\"0\" frame border=\"0\">";

echo "<tr align = \"left\">";
echo "<td>";
echo "
<span class=\"polecam\">

Podejmujemy wspó³pracê na zasadach <b>Umowy Otwartej</b> i <b>Umowy z Klauzul± Wy³±czno¶ci</b>.<br><br>
Z przyjemno¶ci± przy tym obserwujemy na rynku tworz±c± siê grupê nabywców zainteresowanych us³ugami agencji nieruchomo¶ci, chc±cych mieæ zapewnione bezpieczeñstwo transakcji, gdzie nierzadko w grê wchodzi dorobek ca³ego ¿ycia, b±d¼ perspektywa wieloletniej sp³aty kredytu. Nasze biuro dysponuje równie¿ baz± danych potencjalnych klientów spoza Opola, którzy nie maj±c dostêpu do lokalnej prasy, nie bêd± w stanie zainteresowaæ siê ofertami sprzedaj±cych indywidualnie, a zatem powierzaj± nam poszukiwanie dla siebie nieruchomo¶ci na terenie miasta i okolic.<br><br>

<b>CO DAJE WY£¡CZNO¦Æ ?</b><br><br>
Umowy z klauzul± wy³±czno¶ci s± najlepsz± form± sprzeda¿y nieruchomo¶ci i to nie tylko z punktu widzenia po¶rednika ale tak¿e sprzedaj±cego. Jest to podstawowy sposób dzia³alno¶ci po¶redników na rynku zachodnim, który znakomicie sprawdza siê równie¿ w polskich realiach.<br><br>

<b>1. OSZCZÊDNO¦Æ CZASU I PIENIÊDZY.</b><br><br>
Umowa zobowi±zuje po¶rednika do ca³ego szeregu dzia³añ w sferze promocji i reklamy, w tym powierzenia oferty innym biurom (co odpowiada zg³oszeniu oferty do kilkudziesiêciu biur w ca³ym województwie). Podejmuj±c siê samemu tej czynno¶ci pierwszy miesi±c zajmie sprzedaj±cemu na umawianie siê z po¶rednikami, odpowiadanie na te same pytania, analizowanie umów, okazywanie obiektu. Dzia³ania te, na pewno czasoch³onne, mog± okazaæ siê równie¿ do¶æ kosztowne w przypadku gdy oferowana nieruchomo¶æ le¿y poza faktycznym miejscem zamieszkania sprzedaj±cego.<br><br>

<b>2. WZROST SKUTECZNO¦CI.</b><br><br>
Maj±c podpisan± umowê na wy³±czno¶æ Biuro jest w stanie prowadziæ szersz± politykê sprzeda¿y. Podaj±c wiêksz± ilo¶æ informacji, lokalizacjê, zdjêcia budynku z zewn±trz, w sposób bardziej trafny jest w stanie wyselekcjonowaæ grupê potencjalnych nabywców. Przykuæ ich zainteresowanie og³oszeniami w prasie czy w ofercie internetowej. Taki sposób prezentacji w praktyce przynosi nawet <b>40 % !!!</b> wzrost skuteczno¶ci. Biuro pewnie wydatkuje swoje pieni±dze maj±c zagwarantowane wynagrodzenie w przypadku sprzeda¿y.<br><br>

<b>3. ZYSKI.</b><br><br>
Mo¿liwo¶æ szerokiej reklamy, w po³±czeniu ze wspó³prac± i korzystaniem z baz danych innych biur po¶rednictwa pozwala na uzyskanie maksymalnie dobrej ceny rynkowej. Cenê t± zap³aci bowiem klient wyselekcjonowany z du¿ej grupy potencjalnych nabywców.<br><br>

<br>
</span>";
echo "</td>";
echo "</tr>";
echo "</table>";
echo "</center>";
?>
