<?
echo "
<center>
<span class=\"nag2b\">
<b>Informacje dla Klienta</b>
</span>
</center>
<br>
<br>";
echo "<center>";
echo "<table width=\"500\" cellpadding=\"0\" cellspacing=\"0\" frame border=\"0\">";

echo "<tr align = \"left\">";
echo "<td>";
echo "
<span class=\"polecam\">
Przy wyborze biura nieruchomo¶ci, z którym chc± Pañstwo podj±æ wspó³pracê, nale¿y zwróciæ uwagê na nastêpuj±ce rzeczy:
<ul type=\"1\">
<li>Czy biuro ma licencjowanego po¶rednika w obrocie nieruchomo¶ciami ?
<li>Czy biuro ubezpieczone jest od odpowiedzialno¶ci cywilnej ?
<li>Jak d³ugo biuro dzia³a na rynku ?
<li>Czy biuro stowarzyszone jest w jaki¶ organizacjach zrzeszaj±cych profesjonalnych po¶redników w obrocie nieruchomo¶ciami ?
<li>Czy biuro obecne jest w lokalnej prasie i Internecie by w sposób efektywny móc promowaæ i reklamowaæ Pañstwa nieruchomo¶æ ?
</ul>
Wybór odpowiedniego <b>Biura Po¶rednictwa</b> w obrocie nieruchomo¶ci jest gwarancj± zawi±zania wspó³pracy z odpowiednim i profesjonalnym partnerem, owocuj±cej wymiernymi sukcesami w sprzeda¿y Pañstwa nieruchomo¶ci.
<br>
</span>";
echo "</td>";
echo "</tr>";
echo "</table>";
echo "</center>";
?>
