<?
echo "
<center>
<span class=\"nag2b\">
<b>KONTAKT</b>
</span>
</center>
<br><br><br>
<table align=\"center\" width=\"500\">
<tr>
<td align=\"left\">
<span class=\"polecam\">
<center>
<b>OPOLSKIE BIURO NIERUCHOMO¦CI<br>
A.Z.GWARANCJA<br><br></b>
</center>
ul. Bytnara Rudego 13, 45-284 OPOLE<br>
Czynne: pn. - pt. 10.00 - 18.00, sob. 10.00 - 14.00<br>
tel./fax (0 77) 458-00-94, tel.kom. 0602-531-334<br>
<br>
<b>FILIA</b>
<br><br>
Budynek Spó³dzielni Mieszkaniowej ZWM<br>
I piêtro, pokój 118 A<br>
ul. Sosnkowskiego 40-42, 45-284 OPOLE<br>
Czynne: pn. - pt. 10.00 - 15.00, wt. 10.00 - 17.00<br>
tel./fax (0 77) 457-96-99<br>
Poczta: <a href=\"mailto:azgwarancja@azg.pl\">azgwarancja@azg.pl</a><br>
Adres www: <a href=\"http://www.azg.pl\">www.azg.pl</a>
</span>
</td>
<td align=\"center\">
<a href=\"image.php?p=img/mapa&w=600&h=400&i=Mapa\" onclick=\"NewWindow(this.href,'name','620','420','no');return false;\">
	<img src=\"img/mapa_s.jpg\" width=\"175\" height=\"125\" border=\"0\" alt=\"Mapa Lokalizacyjna\"></a><br><span class=\"info\">
	<a href=\"image.php?p=img/mapa&w=600&h=400&i=Mapa\" onclick=\"NewWindow(this.href,'name','620','420','no');return false;\">
	Kliknij, aby powiêkszyæ<br>mapê lokalizacyjn± firmy.</a>
</span>
</td>
</tr>
</table>
";
?>