<?
    class tags
    {
        public static $wyloguj = '_wyloguj';
        public static $zmianajezyka = '_zmiana_jezyka';
        public static $zatwierdz = '_zatwierdz';
        public static $zmiana_hasla = '_zmiana_hasla';
        public static $login = '_login';
        public static $haslo = '_haslo';
        public static $nowe = '_nowe';
        public static $stare = '_stare';
        public static $potwierdz = '_potwierdz';
        public static $niezgodne = '_niezgodne';
        public static $nazwisko = '_nazwisko';
        public static $numer = '_numer';
        public static $oferty = '_oferty';
        public static $numer_oferty = '_numer_oferty';
        public static $szukaj = '_szukaj';
        public static $miejscowosc = '_miejscowosc';
        public static $imie = '_imie';
        public static $cena = '_cena';
        public static $rodzaj_transakcja = '_rodzaj_transakcja';
        public static $rodzaj_nieruchomosci  = '_rodzaj_nieruchomosci';
        public static $edytuj = '_edytuj';
        public static $kasuj = '_kasuj';
        public static $dodaj = '_dodaj';
        public static $cena_transakcji = '_cena_transakcji';
        public static $rodzaj_budynek = '_rodzaj_budynek';
        public static $agent = '_agent';
        public static $klient = '_klient';
        public static $osobowosc = '_osobowosc';
        public static $id = '_id';
        public static $region_geog = array('_kraj', '_wojewodztwo', '_powiat', '_gmina', '_miejscowosc', '_dzielnica');
        public static $wojewodztwo = '_wojewodztwo';
        public static $powiat = '_powiat';
        public static $wybierz = '_wybierz';
        public static $operacja_nie_powiodla_sie = '_operacja_nie_powiodla_sie';
        public static $operacja_powiodla_sie = '_operacja_powiodla_sie';
        public static $nazwisko_rodowe = '_nazwisko_rodowe';
        public static $nr_dowod = '_nr_dowod';
        public static $zbyt_wiele_wynikow = '_zapytanie_zwrocilo_zbyt_wiele_wynikow';
        public static $pesel = '_pesel';
        public static $dodaj_do_klienta = '_dodaj_do_klienta';
        public static $nazwa_firma = '_nazwa_firma'; 
        public static $nip = '_nip';
        public static $regon = '_regon';
        public static $krs = '_krs';        
        public static $kod_pocztowy = '_kod_pocztowy';
        public static $ulica = '_ulica';
        public static $nr_dom = '_numer_dom';
        public static $nr_mieszkanie = '_numer_mieszkanie';
        public static $ist_klient = '_istniejacy_klient';
        public static $status = '_status';
        public static $data_otw_zlec = '_data_otwarcia_zlecenia';
        public static $data_zam_zlec = '_data_zamkniecia_zlecenia';
        public static $podano_data_przeszlosc = '_podano_date_w_przeszlosci';
        public static $podana_inf_nie_jest_data = '_podana_informacja_nie_jest_data';
        public static $data_koncowa_mniejsza_poczatkowa = '_data_koncowa_jest_mniejsza_od_poczatkowej';
        public static $data_poczatkowa_wieksza_koncowa = '_data_poczatkowa_jest_wieksza_od_koncowej';
        public static $prowizja = '_prowizja';
        public static $prowizja_proc = '_prowizja_podana_w_proc';
        public static $podana_prow_wyd_sie_proc = '_podana_prowizja_wydaje_sie_proc';
        public static $podana_prow_wyd_sie_liczba = '_podana_prowizja_wydaje_sie_liczba';
        public static $wylacznosc = '_wylacznosc';
        public static $pokaz_na_stronie = '_publikuj_na_stronie';
        public static $rynek_pierwotny = '_rynek_pierwotny';
        public static $dostepne = '_dostepne';
        public static $wybrane = '_wybrane';
        public static $podpisano = '_podpisano';
        public static $osoba = '_osoba';
        public static $zmiana_cena = '_zmiana_ceny';
        public static $zmiana_status = '_zmiana_statusu';
        public static $pomieszczenia = '_pomieszczenia';
        public static $dodano = '_dodano';
        public static $usunieto = '_usunieto';
        public static $pomieszczenie = '_pomieszczenie';
        public static $nr_pomieszczenia = '_nr_pomieszczenia';
        public static $zdjecia = '_zdjecia';
        public static $zdjecie = '_zdjecie';
        public static $filmy = '_filmy';
        public static $blad_zakladanie_katalog = '_blad_przy_zakladaniu_katalogu';
        public static $oferta = '_oferta';
        public static $zapotrzbowanie = '_zlecenie';
        public static $zapotrzebowanie = '_zlecenie';
        public static $numer_zapotrzebowania = '_numer_zlecenia';
        public static $zalogowany = '_zalogowany';
        public static $pozostalo = '_pozostalo';
        public static $dni_do_wygasniecia_hasla = '_dni_do_wygasniecia_hasla';
        public static $id_agenta = '_id_agenta';
        public static $dodaj_zapotrzebowanie = '_dodaj_zlecenie';
        public static $poszukiwane_nieruchomosci = '_poszukiwane_nieruchomosci';
        public static $zamknij = '_zamknij';
        public static $pokaz_skojarzenia = '_pokaz_skojarzenia';
        public static $poziom_kojarzenia_parametrow = '_poziom_kojarzenia_parametrow';
        public static $poziom_kojarzenia_wyposazen = '_poziom_kojarzenia_wyposazen';
        public static $brak = '_brak';
        public static $poziom = '_poziom';
        public static $lokalizacja = '_lokalizacja';
        public static $wybrane_lokalizacje_poszukiwanej_nieruchomosci = '_wybrane_lokalizacje_poszukiwanej_nieruchomosci';
        public static $dokument_tozsamosci = '_dokument_tozsamosci';
        public static $nr_dokument_tozsamosci = '_numer_dokumentu_tozsamosci';
        public static $telefon = '_telefon';
        public static $telefon_komorkowy = '_telefon_komorkowy';
        public static $adres_email = '_adres_email';
        public static $opis = '_opis';
        public static $opis_zapotrzebowania = '_opis_zlecenia';
        public static $dokumenty = '_dokumenty';
        public static $kontakt = '_kontakt';
        public static $aktualizuj = '_aktualizuj';
        public static $istniejaca_osoba = '_istniejaca_osoba';
        public static $wlasciciele = '_wlasciciele';
        public static $szczegoly = '_szczegoly';
        public static $proc_udzial = '_procent_udzial';
        public static $lista_wskazan = '_lista_wskazan';
        public static $data = '_data';
        public static $godzina = '_godzina';
        public static $osoby_dostepne = '_osoby_dostepne';
        public static $notatka = '_notatka';
        public static $wybrane_oferty = '_wybrane_oferty';
        public static $osoby_ogladajace = '_osoby_ogladajace';
        public static $generuj_liste_wskazan = '_generuj_liste_wskazan';
        public static $biuro_nieruchomosci = '_biuro_nieruchomosci';
        public static $lista_wskazan_adresowych = '_lista_wskazan_adresowych';
        public static $minuta = '_minuta';
        public static $opis_oferty = '_opis_oferty';
        public static $klienci = '_klienci';
        public static $osoba_otwiera_zlecenie = '_osoba_otwierajaca_zlecenie';
        public static $numer_klienta = '_numer_klienta';
        public static $dodawanie_osoby = '_dodawanie_osoby';
        public static $osoby_dodane = '_osoby_dodane';
        public static $edycja_osoby = '_edycja_osoby';
        public static $edycja_klienta = '_edycja_klienta';
        public static $szukanie_istniejacych_osob = '_szukanie_istniejacych_osob';
        public static $szukanie_istniejacych_ofert = '_szukanie_istniejacych_ofert';
        public static $szukanie_istniejacych_zapotrzebowan = '_szukanie_istniejacych_zapotrzebowan';
        public static $znalezione_osoby = '_znalezione_osoby';
        public static $dodawanie_nowej_oferty = '_dodawanie_nowej_oferty';
        public static $dodano_oferte = '_dodano_oferte';
        public static $szukanie_klienta = '_szukanie_klienta';
        public static $pokaz = '_pokaz';
        public static $podstrony = '_podstrony';
        public static $zapotrzebowania = '_zlecenia';
        public static $dodaj_oferte = '_dodaj_oferte';
        public static $media = '_media';
        public static $listy_wskazan_nie_wprowadzone = '_listy_wskazan_nie_wprowadzone_do_systemu';
        public static $nie_znaleziono_elementow = '_nie_znaleziono_elementow';
        public static $nr_osoby = '_nr_osoby';
        public static $nr_oferty = '_nr_oferty';
        public static $nr_klienta = '_nr_klienta';
        public static $nr_zapotrzebowania = '_nr_zlecenia';
        public static $cel_spotkania = '_cel_spotkania';
        public static $pokazywanie = '_pokazywanie';
        public static $umow = '_umow';
        public static $pokazywania_nieuzgodnione = '_pokazywania_nieuzgodnione';
        public static $pokazywania_uzgodnione = '_pokazywania_uzgodnione';
        public static $uzgadnianie_pokazywania_z_oferentem = '_uzgadnianie_pokazywania_z_oferentem';
        public static $osoby_pokazujace = '_osoby_pokazujace';
        public static $dodawanie_nieruchomosci_z_mediow = '_dodawanie_nieruchomosci_z_mediow';
        public static $oferuje = '_oferuje';
        public static $poszukuje = '_poszukuje';
        public static $powierzchnia = '_powierzchnia';
        public static $rodzaj_medium = '_rodzaj_medium';
        public static $data_przypomnienia = '_data_przypomnienia';
        public static $komentarz = '_komentarz';
        public static $znaleziono_w_mediach = '_znaleziono_w_mediach';
        public static $biezace = '_biezace';
        public static $moje = '_moje';
        public static $wszystkie = '_wszystkie';
        public static $przypomnienia_z_ostatnich_trzech_miesiecy = '_przypomnienia_z_ostatnich_trzech_miesiecy';
        public static $przypomnienia = '_przypomnienia';
        public static $reklamowanie = '_reklamowanie';
        public static $aplikacje = '_aplikacje';
        public static $kalendarz = '_kalendarz';
        public static $skojarzone_z_mediow = '_skojarzone_z_mediow';
        public static $dodawanie_do_kalendarza = '_dodawanie_do_kalendarza';
        public static $aktualizacja_kalendarza = '_aktualizacja_kalendarza';
        public static $znaleziono_rekordow = '_znaleziono_rekordow';
        public static $lokalizacja_internet = '_lokalizacja_(internet)';
        public static $dodawanie_zapotrzebowania = '_dodawanie_zlecenia';
        public static $notatka_wewnetrzna = '_notatka_wewnetrzna_do_zlecenia_ogolna';
        public static $zapotrzebowania_skojarzone_dla_oferty = '_zlecenia_skojarzone_dla_oferty';
        public static $oferty_skojarzone_dla_zapotrzebowania = '_oferty_skojarzone_dla_zlecenia';
        public static $bledny_tel_kom = '_bledny_telefon_komorkowy';
        public static $bledny_telefon = '_bledny_telefon';
        public static $bledny_kod = '_bledny_kod_pocztowy';
        public static $bledny_pesel = '_bledny_pesel';
        public static $osoby_powiazane = '_osoby_powiazane';
        public static $osoby_powiazane_z_oferta = '_osoby_powiazane_z_oferta';
        public static $oferent = '_oferent';
        public static $planowanie_ogladania_oferty = '_planowanie_ogladania_oferty';
        public static $informacje_o_ofercie = '_informacje_o_ofercie';
        public static $zaplanowane_klientowi_ogladania = '_zaplanowane_klientowi_ogladania';
        public static $pokazywania_uzgodnione_dla_oferty = '_pokazywania_uzgodnione_dla_oferty';
        public static $przygotuj_liste = '_przygotuj_liste';
        public static $brak_ofert = '_brak_ofert';
        public static $powiadom_administratora = '_powiadom_administratora';
        public static $ogladania_zaplanowane_klientowi_przez_innych_agentow = '_ogladania_zaplanowane_klientowi_przez_innych_agentow';
        public static $drukuj_umowe = '_drukuj_umowe';
        public static $waznosc_oferty = '_waznosc_oferty';
        public static $blad_publikacji_w_serwisie_otodom = '_blad_publikacji_w_serwisie_otodom';
        public static $opublikowano_oferte_w_serwisie_otodom = '_opublikowano_oferte_w_serwisie_otodom';
        public static $podpis_klienta = '_podpis_klienta';
        public static $podpis_agenta = '_podpis_agenta';
        public static $adres = '_adres';
        public static $kupna = '_kupna';
        public static $najmu = '_najmu';
        public static $klucze_w_biurze = '_klucze_w_biurze';
        public static $wybor_klienta = '_wybor_klienta';
        public static $wybor_osoby = '_wybor_osoby';
        public static $czas_przekazania_m = '_czas_przekazania(miesiecy)';
        public static $czas_liczony_od_otwarcia = '_czas_liczony_od_otwarcia_zlecenia';
        public static $dodaj_jako = '_dodaj_jako';
        public static $tak = '_tak';
        public static $nie = '_nie';
        public static $ogladania_uzgodnione_dla_oferty = '_ogladania_uzgodnione_dla_oferty';
        public static $ogladanie = '_ogladanie';
        public static $szukaj_oferty = '_szukaj_oferty';
        public static $szukaj_klienta = '_szukaj_klienta';
        public static $szukaj_zapotrzebowania = '_szukaj_zlecenia';
        public static $szukaj_w_mediach = '_szukaj_w_mediach';
        public static $dodawanie_nowego_klienta = '_dodawanie_nowego_klienta';
        public static $wyswietl_oferty = '_wyswietl_oferty';
        public static $wyswietl_zapotrzebowania = '_wyswietl_zlecenia';
        public static $dodano_klienta = '_dodano_klienta';
        public static $wybierz_rodzaj_oferty = '_wybierz_rodzaj_oferty';
        public static $dalej = '_dalej';
        public static $wyzej = '_wyzej';
        public static $nizej = '_nizej';
        public static $wszyscy = '_wszyscy';
        public static $skojarz = '_skojarz';
        public static $powierzchnia_max = '_powierzchnia_max';
        public static $preferencje_klienta = '_preferencje_klienta';
        public static $liczba_pokoi = '_liczba_pokoi';
        public static $liczba_pokoi_max = '_liczba_pokoi_max';
        public static $oferty_ogladniete_przez_klienta = '_oferty_ogladniete_przez_klienta';
        public static $notatki = '_notatki';
        public static $kalendarz_na_dzien = '_kalendarz_na_dzien';
        public static $brak_informacji_do_wyswietlenia = '_brak_informacji_do_wyswietlenia';
        public static $notatka_do_zapotrzebowania = '_notatka_do_zlecenia';
        public static $sposob_finansowania = '_sposob_finansowania';
        public static $poszukuje_dla = '_poszukuje_dla';
        public static $posiada_do_sprzedazy_wynajmu = '_posiada_do_sprzedazy_wynajmu'; //Posiada do sprzeda¿y/wynajmu
        public static $poszukuje_do_kupna_najmu = '_poszukuje_do_kupna_najmu'; //Poszukuje do kupna/najmu (!!!)
        public static $wprowadzanie_nieruchomosci_poszukiwanej_oferowanej = '_wprowadzanie_nieruchomosci_poszukiwanej_oferowanej'; //Wprowadzanie nieruchomoœci poszukiwanej/oferowanej
        public static $oferty_zapotrzebowania_znajdujace_sie_w_mediach = '_oferty_zlecenia_osoby_znajdujace_sie_w_mediach'; //Oferty/zapotrzebowania osoby znajduj¹ce siê w mediach
        public static $edycja_oferty_zapotrzebowania_w_mediach = '_edycja_oferty_zlecenia_w_mediach';
        public static $szczegolowy_opis = '_szczegolowy_opis';
        public static $przetwarzanie_ofert = '_przetwarzanie_ofert';
        public static $edycja_oferty = '_edycja_oferty';
        public static $lic_zaw_nr = '_lic_zaw_nr';
        public static $podpisano_umowe_oferta_nr = '_podpisano_umowe_oferta_nr';
        public static $podpisano_umowe_zlecenie_nr = '_podpisano_umowe_zlecenie_nr';
        public static $przyjeto_jako_oferte_nr = '_przyjeto_jako_oferte_nr';
        public static $przyjeto_jako_zlecenie_nr = '_przyjeto_jako_zlecenie_nr';
        public static $oferta_zlecenie_przypisane_z_mediow = '_oferta_zlecenie_przypisane_z_mediow';
        public static $wskaz_oferte_zlecenie_w_mediach = '_wskaz_oferte_zlecenie_w_mediach';
        public static $data_od = '_data_od';
        public static $data_do = '_data_do';
        public static $data_godz = '_data_godz';
        public static $przetwarzanie_zlecen = '_przetwarzanie_zlecen';
        public static $telefony_kontaktowe = '_telefony_kontaktowe';
        public static $lista_oferentow = '_lista_oferentow';
        public static $pokazuje = '_pokazuje';
        public static $zmiana_terminu = '_zmiana_terminu';
        public static $osoby_powiazane_z_klientem = '_osoby_powiazane_z_klientem';
        public static $otwieranie_nowych_zlecen = '_otwieranie_nowych_zlecen_lub_ofert';
        public static $akceptowana_lokalizacja_poszukiwanej_nieruchomosci = '_akceptowana_lokalizacja_poszukiwanej_nieruchomosci';
        public static $nie_znaleziono_oferty_o_podanym_numerze = '_nie_znaleziono_oferty_o_podanym_numerze';
        public static $dodawanie_nowego_pomieszczenia = '_dodawanie_nowego_pomieszczenia';
        public static $edycja_pomieszczenia = '_edycja_pomieszczenia';
        public static $zakoncz = '_zakoncz';
        public static $geografia = '_geografia';
        public static $szczegolowe_oczekiwania = '_szczegolowe_oczekiwania';
        public static $opis_poszukiwanych_nieruchomosci = '_opis_poszukiwanych_nieruchomosci';
        public static $oferty_ogladniete = '_oferty_ogladniete';
        public static $ma_dzieci = '_ma_dzieci';
        public static $zaglebienie = '_zaglebienie';
        public static $niezainteresowany = '_niezainteresowany';
        public static $zainteresowany = '_zainteresowany';
        public static $notatki_do_ofert = '_notatki_do_ofert';
        public static $oferta_jest_juz_na_liscie_wskazan = '_oferta_jest_juz_na_liscie_wskazan_lub_nie_jest_aktualna';
        public static $id_otodom = '_id_otodom';
        public static $agenci = '_agenci';
        public static $fax = '_fax';
        public static $druk = '_druk';
        public static $adm_kl = '_adm_kl';
        public static $adm_dane = '_adm_dane';
        public static $zm_upr = '_zm_upr';
        public static $aktywne = '_aktywne';
        public static $waznosc_hasla = '_waznosc_hasla';
        public static $priorytet = '_priorytet';
        public static $od_zaraz = '_od_zaraz';
        public static $wyslij = '_wyslij';
        public static $notatka_o_kliencie = '_notatka_o_kliencie';
        public static $dodanie_ogladania_oferty = '_dodanie_ogladania_oferty';
        public static $uzgodniono_ogladanie_oferty = '_uzgodniono_ogladanie_oferty';
        public static $wybierz_osoby_ogladajace = '_wybierz_osoby_ogladajace';
        public static $oferty_z_ostatnich_trzech_miesiecy = '_oferty_z_ostatnich_trzech_miesiecy';
        public static $wyslano_maili = '_wyslano_maili';
        public static $link_do_oferty = '_link_do_oferty';
        public static $dostarczona_wiadomosc_nie_jest_spamem = '_dostarczona_wiadomosc_nie_jest_spamem___';
        public static $tutaj = '_tutaj';
        public static $dodano_wpis = '_dodano_wpis';
        public static $wprowadzanie_masowe = '_wprowadzanie_masowe';
        public static $cena_m2 = '_cena_m2(PLN)';
        public static $cofnij = '_cofnij';
        public static $weryfikacja_kalendarza = '_weryfikacja_kalendarza';
        public static $opis_poszukiwanej_nieruchomosci = '_opis_poszukiwanej_nieruchomosci';
        public static $generuj_liste_ogladanych_ofert = '_generuj_liste_ogladanych_ofert';
        public static $bledny_e_mail = '_bledny_e_mail';
        public static $telefony_przychodzace = '_telefony_przychodzace';
        public static $opublikowano_oferte_w_serwisie_domiporta = '_opublikowano_oferte_w_serwisie_domiporta';
        public static $faktury = '_faktury';
        public static $nr_faktury = '_nr_faktury';
        public static $data_wystawienia = '_data_wystawienia';
        public static $data_sprzedazy = '_data_sprzedazy';
        public static $forma_platnosci = '_forma_platnosci';
        public static $termin_platnosci = '_termin_platnosci';
        public static $przelew = '_przelew';
        public static $gotowka = '_gotowka';
        public static $kwota_uslugi_netto = '_kwota_uslugi_netto';
        public static $nazwa_uslugi = '_nazwa_uslugi';
        public static $imie_nazwisko_nazwa_nabywcy = '_imie_nazwisko_nazwa_nabywcy';
        public static $adres_zamieszkania_lub_siedziba_nabywcy = '_adres_zamieszkania_lub_siedziba_nabywcy';
        public static $rachunek = '_rachunek';
        public static $miesiac = '_miesiac';
        public static $rok = '_rok';
        public static $drukuj_oryginal = '_drukuj_oryginal';
        public static $drukuj_kopie = '_drukuj_kopie';
        public static $dodaj_agent = '_dodaj_agent';
        public static $imie_i_nazwisko = '_imie_i_nazwisko';
        public static $skrot = '_skrot';
        public static $haslo_ponownie = '_haslo_ponownie';
        public static $haslo_jest_za_krotkie = '_haslo_jest_za_krotkie';
        public static $hasla_sa_niezgodne = '_hasla_sa_niezgodne';
        public static $wewnetrzny = '_wewnetrzny';
        public static $nip_jest_niepoprawny = '_nip_jest_niepoprawny';
        public static $dodawanie_nowego_agenta = '_dodawanie_nowego_agenta';
        public static $uprawnienia = '_uprawnienia';
        public static $nr_licencji = '_nr_licencji';
        public static $nazwa_banku = '_nazwa_banku';
        public static $niepoprawny_nr_rachunku = '_niepoprawny_nr_rachunku';
        public static $modyfikacja_agenta = '_modyfikacja_agenta';
        public static $konto_aktywne = '_konto_aktywne';
        public static $znalezieni_klienci = '_znalezieni_klienci';
        public static $oferty_klienta = '_oferty_klienta';
        public static $zlecenia_klienta = '_zlecenia_klienta';
        public static $otwieranie_zlecenia = '_otwieranie_zlecenia';
        public static $dodawanie_rodzaju_transakcji_dla_poszukiwanej_nieruchomosci = '_dodawanie_rodzaju_transakcji_dla_poszukiwanej_nieruchomosci';
        public static $zmiana_danych_o_transakcji_dla_poszukiwanej_nieruchomosci = '_zmiana_danych_o_transakcji_dla_poszukiwanej_nieruchomosci';
        public static $wprowadzanie_prowizji_biura = '_wprowadzanie_prowizji_biura';
        public static $dodawanie_istniejacej_osoby_do_klienta = '_dodawanie_istniejacej_osoby_do_klienta';
        public static $dodawanie_nowej_osoby_do_klienta = '_dodawanie_nowej_osoby_do_klienta';
        public static $przygotowywanie_listy_wskazan_po_numerze_ofert = '_przygotowywanie_listy_wskazan_po_numerze_ofert';
        public static $znalezione_lokalizacje = '_znalezione_lokalizacje';
        public static $notatka_wewnetrzna_do_nieruchomosci = '_notatka_wewnetrzna_do_nieruchomosci';
        public static $lista_klientow_ktorzy_obejrzeli_nieruchomosci = '_lista_klientow_ktorzy_obejrzeli_nieruchomosci';
        public static $historia_zmian_ceny = '_historia_zmian_ceny';
        public static $historia_zmian_statusu = '_historia_zmian_statusu';
        public static $oferta_w_mediach = '_oferta_w_mediach';
        public static $data_dodania_od = '_data_dodania_od';
        public static $data_dodania_do = '_data_dodania_do';
        public static $rynek_wtorny = '_rynek_wtorny';
        public static $rodzaj_rynek = '_rodzaj_rynku';
        public static $informacje_ogolne = '_informacje_ogolne';
        public static $nowa_oferta_w_biurze_nieruchomosci = '_nowa_oferta_w_biurze_nieruchomosci';
        public static $gablota = '_gablota';
        public static $oferta_w_naszym_biurze = '_oferta_w_naszym_biurze';
        public static $oferta_na_wylacznosc = '_oferta_na_wylacznosc';
        public static $prowadzacy_oferte = '_prowadzacy_oferte';
        public static $wiecej_informacji_na_stronie_internetowej = '_wiecej_informacji_na_stronie_internetowej';
        public static $maksymalna_liczba_elementow = '_maksymalna_liczba_elementow';
        public static $nie_zaznaczono_zdjecia = '_nie_zaznaczono_zdjecia';
        public static $minimalna_liczba_elementow = '_minimalna_liczba_elementow';
        public static $administracja = '_administracja';
        public static $typ_nieruchomosci = '_typ_nieruchomosci';
        public static $wiecej_o_nieruchomosci = '_wiecej_o_nieruchomosci';
        public static $zdjecie_nieruchomosci = '_zdjecie_nieruchomosci';
        public static $jezyki = '_jezyki';
        public static $wybierz_jezyk = '_wybierz_jezyk';
        public static $wyrazenia_nieprzetlumaczone = '_wyrazenia_nieprzetlumaczone';
        public static $dodaj_kod_wyrazenia = '_dodaj_kod_wyrazenia';
        public static $przebuduj_cache_jezykow = '_przebuduj_cache_jezykow';
        public static $opublikuj_w_portalach = '_opublikuj_w_portalach';
        public static $dowolny_adres_email = '_dowolny_adres_email';
        public static $wysylanie_oferty_mailem_do_innych_biur = '_wysylanie_oferty_mailem_do_innych_biur';
        public static $oferty_wyslane_mailem = '_oferty_wyslane_mailem';
        public static $zlecenia_powiadomione_mailem = '_zlecenia_powiadomione_mailem';
        public static $informacje_o_bankach = '_informacje_o_bankach';
        public static $dodawanie_oferty_banku_przedstawionej_klientowi = '_dodawanie_oferty_banku_przedstawionej_klientowi';
        public static $oferty_bankow_przedstawione_klientowi = '_oferty_bankow_przedstawione_klientowi';
        public static $bank = '_bank';
        public static $powiadom_banki = '_powiadom_banki';
        public static $sprzedano = '_sprzedano';
        public static $transakcja_zrealizowana_przez_azg = '_transakcja_zrealizowana_przez_azg';
        public static $gazeta = '_gazeta';
        public static $pobierz_plik = '_pobierz_plik';
        public static $dzielnica = '_dzielnica';
        public static $nie_znaleziono_ofert = '_nie_znaleziono_ofert';
        public static $rozwiazanie_umowy = '_rozwiazanie_umowy';
        public static $zaloguj_sie = '_zaloguj_sie';
        public static $ilosc_wyszukiwan = '_ilosc_wyszukiwan';
        public static $ilosc_ofert = '_ilosc_ofert';
        public static $wspolrzedne = '_wspolrzedne';
        public static $powiel = '_powiel';
        public static $slowniki = '_slowniki';
        public static $parametr = '_parametr';
        public static $sekcja = '_sekcja';
        public static $walidacja = '_walidacja';
        public static $dlugosc = '_dlugosc';
        public static $waga = '_waga';
        public static $wielokrotne = '_wielokrotne';
        public static $szablon_umowy = '_szablon_umowy';
        public static $podaj_oferty_oddzielone_przecinkiem = '_podaj_oferty_oddzielone_przecinkiem';
        //public static $oferty_agenta = '_oferty_agenta'; //to juz chyba niepotrzebne
        
        /////strona tagi
        public static $mieszkania = '_mieszkania';
        public static $domy = '_domy';
        public static $lokale = '_lokale';
        public static $obiekty = '_obiekty';
        public static $dzialki = '_dzialki';
        public static $tereny = '_tereny';
        public static $kupno = '_kupno';
        public static $sprzedaz = '_sprzedaz';
        public static $najem = '_najem';
        public static $wynajem = '_wynajem';
        public static $zamiana = '_zamiana';
        public static $pokojowe = '_pokojowe';
        public static $oferta_zawieszona = '_oferta_zawieszona';
        public static $wiecej = '_wiecej';
        public static $posrednik = '_posrednik';
        public static $licencja = '_licencja:';
        public static $agent_pod_nadzorem_licencji_nr = '_agent_pod_nadzorem_licencji_nr:';
        public static $poprzednio = '_poprzednio';
        public static $wydrukuj_ze_zdjeciami = '_wydrukuj_ze_zdjeciami';
        public static $wydrukuj_bez_zdjec = '_wydrukuj_bez_zdjec';
        public static $zdjecia_oferty = '_zdjecia_oferty';
        public static $oferty_specjalne = '_oferty_specjalne';
        public static $polecamy = '_polecamy';
        public static $nowe_inwestycje = '_nowe_inwestycje';
        public static $nowe_inwestycje_domow_jednorodzinnych = '_nowe_inwestycje_domow_jednorodzinnych';
        public static $nowosci = '_nowosci';
        public static $subskrypcja_biura_nieruchomosci = '_subskrypcja_biura_nieruchomosci';
        public static $subskrypcja = '_subskrypcja';
        public static $szukam_nieruchomosci = '_szukam_nieruchomosci';
        public static $wedlug_ceny = '_wedlug_ceny';
        public static $od = '_od';
        public static $do = '_do';
        public static $do_ceny = '_do_ceny';
        public static $podaj_swoj_email = '_podaj_swoj_email';
        public static $nieruchomosci = '_nieruchomosci';
        public static $nieruchomosc = '_nieruchomosc';
        public static $imieniny = '_imieniny';
        public static $znajdz_oferte = '_znajdz_oferte';
        public static $znajdz_nieruchomosci = '_znajdz_nieruchomosci';
        public static $zglos_oferte = '_zglos_oferte';
        public static $zglos_nieruchomosc = '_zglos_nieruchomosc';
        public static $ul = '_ul'; //skrot ulica :P
        public static $mapa_lokalizacyjna = '_mapa_lokalizacyjna'; 
        public static $nalezymy_do = '_nalezymy_do'; 
        public static $formularz = '_formularz'; 
        public static $filia = '_filia'; 
        public static $oblicz = '_oblicz'; 
        public static $nr = '_nr';
        public static $np = '_np';
        public static $kliknij_ponizszy_link = '_kliknij_ponizszy_link';
        public static $kalkulator_oplat = '_kalkulator_oplat_notarialnych_biura_nieruchomosci';
        public static $cena_nieruchomosci = '_cena_nieruchomosci';
        public static $wysokosc_prowizji_biura = '_wysokosc_prowizji_biura';
        public static $prowizja_biura = '_prowizja_biura';
        public static $wynik_oplat = '_wynik_oplat';
        public static $wydrukuj_oplaty = '_wydrukuj_oplaty';
        public static $podatek_od_czynnosci_cywilnoprawnych = '_podatek_od_czynnosci_cywilnoprawnych';
        public static $podatek_vat_od_taksy_notarialnej = '_podatek_vat_od_taksy_notarialnej'; //Podatek VAT od Taksy Notarialnej 
        public static $podatek_vat_od_prowizji_biura = '_podatek_vat_od_prowizji_biura'; //Podatek VAT od Taksy Notarialnej 
        public static $taksa_notarialna = '_taksa_notarialna';
        public static $okolo = '_okolo';
        public static $oplata_sadowa = '_oplata_sadowa';
        public static $wypisy_aktow = '_wypisy_aktow';
        public static $suma_oplat_dodatkowych = '_suma_oplat_dodatkowych';
        public static $suma = '_suma';
        public static $kredyty_hipoteczne = '_kredyty_hipoteczne';
        public static $formy_sprzedazy = '_formy_sprzedazy';
        public static $co_daje_wylacznosc = '_co_daje_wylacznosc';
        public static $oszczednosc_czasu_i_pieniedzy = '_oszczednosc_czasu_i_pieniedzy';
        public static $wzrost_skutecznosci = '_wzrost_skutecznosci';
        public static $zyski = '_zyski';
        public static $i = '_i';
        public static $informacje_dla_klienta = '_informacje_dla_klienta';
        public static $klienta = '_klienta';
        public static $biura_posrednictwa = '_biura_posrednictwa';
        public static $wybor_miejscowosci = '_wybor_miejscowosci';
        public static $umowiona = '_umowiona';
        public static $wstrzymana = '_wstrzymana';
        public static $aktualna = '_aktualna';
        public static $zawieszona = '_zawieszona';
        public static $usun = '_usun';
        public static $powrot = '_powrot';
        public static $cena_minimalna = '_cena_minimalna';
        public static $cena_maxymalna = '_cena_maksymalna';
        public static $nieruchomosci_w_opolu_i_w_wojewodztwie_opolskim = '_nieruchomosci_w_opolu_i_w_wojewodztwie_opolskim';
        public static $w_opolu_i_w_wojewodztwie_opolskim = '_w_opolu_i_w_wojewodztwie_opolskim';
        public static $opole_wojewodztwo_opolskie_ogloszenia_posrednictwo = '_opole_wojewodztwo_opolskie_ogloszenia_posrednictwo';
        public static $ilosc_wyswietlen_oferty_na_stronie = '_ilosc_wyswietlen_oferty_na_stronie';
        public static $statystyki = '_statystyki';
        public static $unikatowych_adresow = '_unikatowych_adresow';
        public static $wspolczynnik = '_wspolczynnik';
        public static $nieruchomosci_podobne_znajdujace_sie_w_ofercie_biura = '_nieruchomosci_podobne_znajdujace_sie_w_ofercie_biura';
        
        public static $mieszkanie_spoldzielcze_wlasnosciowe = '_mieszkanie_spoldzielcze_wlasnosciowe';
        public static $mieszkanie_spoldzielcze_wlasnosciowe_z_ksiega_wieczysta = '_mieszkanie_spoldzielcze_wlasnosciowe_z_ksiega_wieczysta';
        public static $mieszkanie_hipoteczne__dom__dzialka = '_mieszkanie_hipoteczne__dom__dzialka';
        
        public static $aby_otrzymywac_informacje = '_aby_otrzymywac_informacje___'; //Aby otrzymaæ informacje o najnowszych ofertach
        public static $wspolpracujac_z_poszczegolnymi_bankami = '_wspolpracujac_z_poszczegolnymi_bankami___'; //wspó³pracuj¹c z poszczególnymi bankami pomaga klientom w uzyskaniu kredytów finansuj¹cych zakup wybranej nieruchomoœci
        //public static $ = '____';
        public static $kompletujac_oraz_sprawdzajac_cala = '_kompletujac_oraz_sprawdzajac_cala___';//Kompletuj¹c oraz sprawdzaj¹c ca³¹ dokumentacjê nieruchomoœci przyspieszamy proces rozpatrzenia wniosków kredytowych przez Bank
        public static $banki_z_ktorymi = '_banki_z_ktorymi';//Banki z którymi
        public static $podpisalo_umowy_o_wspolprace = '_podpisalo_umowy_o_wspolprace';//podpisa³o umowy o wspó³pracê
        public static $wpisujac_swoj_email_na_biezaco = '_wpisujac_swoj_email_na_biezaco___';//Wpisuj¹c swój E-mail na bie¿¹co bêdziesz informowany o pojawiaj¹cych siê w naszym biurze ofertach, spe³niaj¹cych podane przez ciebie kryteria
        public static $dla_poprawnego_dzialania_subskrypcji = '_dla_poprawnego_dzialania_subskrypcji___';//Dla poprawnego dzia³ania subskrypcji wymagane jest wype³nienie wszystkich pól w obszarze wybranej opcji - kupna lub najmu
        public static $formularz_zgloszeniowy_biura_nieruchomosci = '_formularz_zgloszeniowy_biura_nieruchomosci';//FORMULARZ ZG£OSZENIOWY BIURA NIERUCHOMOŒCI
        
        public static $podejmujemy_wspolprace_na_zasadach = '_podejmujemy_wspolprace_na_zasadach';//Podejmujemy wspó³pracê na zasadach
        public static $umowy_otwartej = '_umowy_otwartej';//Umowy Otwartej
        public static $umowy_z_klauzula_wylacznosci = '_umowy_z_klauzula_wylacznosci';//Umowy z Klauzul¹ Wy³¹cznoœci
        public static $z_przyjemnoscia_przy_tym = '_z_przyjemnoscia_przy_tym___';//Z przyjemnoœci¹ przy tym obserwujemy na rynku tworz¹c¹ siê grupê nabywców zainteresowanych us³ugami agencji nieruchomoœci, chc¹cych mieæ zapewnione bezpieczeñstwo transakcji, gdzie nierzadko w grê wchodzi dorobek ca³ego ¿ycia, b¹dŸ perspektywa wieloletniej sp³aty kredytu
        public static $nasze_biuro_dysponuje_rowniez = '_nasze_biuro_dysponuje_rowniez___';//Nasze biuro dysponuje równie¿ baz¹ danych potencjalnych klientów spoza Opola, którzy nie maj¹c dostêpu do lokalnej prasy, nie bêd¹ w stanie zainteresowaæ siê ofertami sprzedaj¹cych indywidualnie, a zatem powierzaj¹ nam poszukiwanie dla siebie nieruchomoœci na terenie miasta i okolic
        public static $umowy_z_klauzula_wylacznosci_sa = '_umowy_z_klauzula_wylacznosci_sa___';//Umowy z klauzul¹ wy³¹cznoœci s¹ najlepsz¹ form¹ sprzeda¿y nieruchomoœci i to nie tylko z punktu widzenia poœrednika ale tak¿e sprzedaj¹cego
        public static $jest_to_podstawowy_sposob = '_jest_to_podstawowy_sposob___';//Jest to podstawowy sposób dzia³alnoœci poœredników na rynku zachodnim, który znakomicie sprawdza siê równie¿ w polskich realiach
        public static $umowa_zobowiazuje_posrednika_do_calego = '_umowa_zobowiazuje_posrednika_do_calego___';//Umowa zobowi¹zuje poœrednika do ca³ego szeregu dzia³añ w sferze promocji i reklamy, w tym powierzenia oferty innym biurom (co odpowiada zg³oszeniu oferty do kilkudziesiêciu biur w ca³ym województwie)
        public static $podejmujac_sie_samemu_tej = '_podejmujac_sie_samemu_tej___';//Podejmuj¹c siê samemu tej czynnoœci pierwszy miesi¹c zajmie sprzedaj¹cemu na umawianie siê z poœrednikami, odpowiadanie na te same pytania, analizowanie umów, okazywanie obiektu
        public static $dzialania_te_na_pewno_czasochlonne = '_dzialania_te_na_pewno_czasochlonne___';//Dzia³ania te, na pewno czasoch³onne, mog¹ okazaæ siê równie¿ doœæ kosztowne w przypadku gdy oferowana nieruchomoœæ le¿y poza faktycznym miejscem zamieszkania sprzedaj¹cego
        public static $majac_podpisana_umowe_na_wylacznosc = '_majac_podpisana_umowe_na_wylacznosc___';//Maj¹c podpisan¹ umowê na wy³¹cznoœæ Biuro jest w stanie prowadziæ szersz¹ politykê sprzeda¿y
        public static $podajac_wieksza_ilosc_informacji = '_podajac_wieksza_ilosc_informacji___';//Podaj¹c wiêksz¹ iloœæ informacji, lokalizacjê, zdjêcia budynku z zewn¹trz, w sposób bardziej trafny jest w stanie wyselekcjonowaæ grupê potencjalnych nabywców
        public static $przykuc_ich_zainteresowanie = '_przykuc_ich_zainteresowanie___';//Przykuæ ich zainteresowanie og³oszeniami w prasie czy w ofercie internetowej
        public static $taki_sposob_prezentacji = '_taki_sposob_prezentacji___';//Taki sposób prezentacji w praktyce przynosi nawet
        public static $biuro_pewnie_wydatkuje = '_biuro_pewnie_wydatkuje___';//Biuro pewnie wydatkuje swoje pieni¹dze maj¹c zagwarantowane wynagrodzenie w przypadku sprzeda¿y
        public static $mozliwosc_szerokiej_reklamy = '_mozliwosc_szerokiej_reklamy___';//Mo¿liwoœæ szerokiej reklamy, w po³¹czeniu ze wspó³prac¹ i korzystaniem z baz danych innych biur poœrednictwa pozwala na uzyskanie maksymalnie dobrej ceny rynkowej
        public static $cene_te_zaplaci_bowiem = '_cene_te_zaplaci_bowiem___';//Cenê t¹ zap³aci bowiem klient wyselekcjonowany z du¿ej grupy potencjalnych nabywców
        public static $przy_wyborze_biura_nieruchomosci = '_przy_wyborze_biura_nieruchomosci___';//Przy wyborze biura nieruchomoœci, z którym chc¹ Pañstwo podj¹æ wspó³pracê, nale¿y zwróciæ uwagê na nastêpuj¹ce rzeczy
        public static $czy_biuro_ma_licencjonowanego = '_czy_biuro_ma_licencjonowanego___';//Czy biuro ma licencjowanego poœrednika w obrocie nieruchomoœciami
        public static $czy_biuro_ubezpieczone_jest = '_czy_biuro_ubezpieczone_jest___';//Czy biuro ubezpieczone jest od odpowiedzialnoœci cywilnej
        public static $jak_dlugo_biuro_dziala = '_jak_dlugo_biuro_dziala___';//Jak d³ugo biuro dzia³a na rynku
        public static $czy_biuro_stowarzyszone_jest = '_czy_biuro_stowarzyszone_jest___';//Czy biuro stowarzyszone jest w jakiœ organizacjach zrzeszaj¹cych profesjonalnych poœredników w obrocie nieruchomoœciami
        public static $czy_biuro_obecne_jest_w_lokalnej = '_czy_biuro_obecne_jest_w_lokalnej___';//Czy biuro obecne jest w lokalnej prasie i Internecie by w sposób efektywny móc promowaæ i reklamowaæ Pañstwa nieruchomoœæ
        public static $wybor_odpowiedniego_biura_posrednictwa = '_wybor_odpowiedniego_biura_posrednictwa___';//Wybór odpowiedniego Biura Poœrednictwa w obrocie nieruchomoœci jest gwarancj¹ zawi¹zania wspó³pracy z odpowiednim i profesjonalnym partnerem, owocuj¹cej wymiernymi sukcesami w sprzeda¿y Pañstwa nieruchomoœci
        public static $dziekujac_za_zainteresowanie_uslugami = '_dziekujac_za_zainteresowanie_uslugami___';//Dziêkuj±c za zainteresowanie us³ugami naszego biura, niniejszym potwierdzamy przyjêcie Pañstwa zg³oszenia.
        public static $zgodnia_z_ustawa_z_dnia = '_zgodnia_z_ustawa_z_dnia___';//Zgodnie z Ustaw± z dnia 29 sierpnia 1997r. o ochronie danych osobowych (Dz. U. nr.133, pozycja  833), wyra¿am zgodê na przetworzenie moich danych osobowych  zawartych w ofercie kupna, sprzeda¿y, najmu, wynajmu.
        
        public static $po_prawidlowym_wypelnieniu_oferty_przycisnij_przycisk = '_po_prawidlowym_wypelnieniu_oferty_przycisnij_przycisk'; //Po prawid³owym wype³nieniu oferty przyci¶nij przycisk
        public static $potwierdzenie_zgloszenia = '_potwierdzenie_zgloszenia';
        public static $szanowni_panstwo = '_szanowni_panstwo';
        public static $siedziba_glowna = '_siedziba_glowna';
        //public static $podaj_cene_nieruchomosci = '_podaj_cene_nieruchomosci';
        public static $wybierz_rodzaj = '_wybierz_rodzaj';
        public static $twoje_zgloszenie_zostalo_przyjete = '_twoje_zgloszenie_zostalo_przyjete';
        
        public static $podaj_swoje_imie_i_nazwisko = '_podaj_swoje_imie_i_nazwisko';
        public static $podaj_telefon_kontaktowy = '_podaj_telefon_kontaktowy';
        public static $wybierz_rodzaj_zgloszenia = '_wybierz_rodzaj_zgloszenia';
        public static $rodzaj_zgloszenia = '_rodzaj_zgloszenia';
        public static $wybierz_przedmiot_zgloszenia = '_wybierz_przedmiot_zgloszenia';
        public static $przedmiot_zgloszenia = '_przedmiot_zgloszenia';
        public static $lokalizacja_nieruchomosci = '_lokalizacja_nieruchomosci';        
        public static $opis_nieruchomosci = '_opis_nieruchomosci';
        
        public static $tel_fax = '_tel_fax';
        public static $tel_kom = '_tel_kom';
        public static $pon = '_pon';
        public static $wt = '_wt';
        public static $sr = '_sr';
        public static $czw = '_czw';
        public static $pt = '_pt';
        public static $sob = '_sob';
        public static $nd = '_nd';
        

        ////koniec tagow strona
        
        ///tagi istniejace na bazie ale potrzebne w panelu - nie tlumaczyc od nowa
        ///otodom
        //media
        public static $prad = '_prad';
        public static $woda = '_woda';
        public static $gaz = '_gaz';
        //public static $telefon = '_telefon';
        public static $kanalizacja = '_kanalizacja';
        public static $siec_internet = '_siec_internet';
        public static $kablowa = '_kablowa';
        //rodzaje budynkow
        public static $wolnostojacy = '_wolnostojacy';
        public static $blizniak = '_blizniak';
        public static $szeregowy = '_szeregowy';
        //rodzaje wlasnosci
        public static $wlasnosc = '_wlasnosc';
        public static $spoldz_wlasnosciowe = '_spoldz__wlasnosciowe';
        //okolice :P 
        public static $las = '_las';
        public static $jezioro = '_jezioro';
        public static $parking = '_parking';
        //usytuowanie
        public static $asfaltowa = '_asfaltowa';
        public static $polna = '_polna';
        public static $utwardzonaszutrowa = '_utwardzona/szutrowa';
        
        public static $styczen = '_styczen';
        public static $luty = '_luty';
        public static $marzec = '_marzec';
        public static $kwiecien = '_kwiecien';
        public static $maj = '_maj';
        public static $czerwiec = '_czerwiec';
        public static $lipiec = '_lipiec';
        public static $sierpien = '_sierpien';
        public static $wrzesien = '_wrzesien';
        public static $pazdziernik = '_pazdziernik';
        public static $listopad = '_listopad';
        public static $grudzien = '_grudzien';
        
        public static $niedziela = '_niedziela';
        public static $poniedzialek = '_poniedzialek';
        public static $wtorek = '_wtorek';
        public static $sroda = '_sroda';
        public static $czwartek = '_czwartek';
        public static $piatek = '_piatek';
        public static $sobota = '_sobota';
        ///koniec otodom
        
        /*public static $osobafizyczna = '_osobafizyczna';
        public static $osobaprawna = '_osobaprawna';*/
        
        ///koniec regionu tagow istniejacych na bazie
        
        //dane z bazy chyba tu nie musza siedziec
        /*public static $dom = '_dom';
        public static $mieszkanie = '_mieszkanie';
        public static $obiekt = '_obiekt';
        public static $lokal = '_lokal';
        public static $teren = '_teren';
        public static $dzialka = '_dzialka';
        public static $sprzedaz = '_sprzedaz';
        public static $wynajem =  '_wynajem';
        public static $zamiana  = '_zamiana';
        public static $dzierzawa =  '_dzierzawa';
        
        public static $sekcjapodstawowa = '_sekcjapodstawowa';
        public static $sekcjadodatkowa = '_sekcjadodatkowa';
        public static $mozliwosczabudowy = '_mozliwosczabudowy';
        public static $informacjetechniczne = '_informacjetechniczne';
        public static $media = '_media';
        public static $zabezpieczenia = '_zabezpieczenia';
        public static $udogodnienia = '_udogodnienia';
        public static $otoczenie = '_otoczenie';
        public static $okolica = '_okolica';
        public static $pokoj = '_pokoj';
        public static $kuchnia = '_kuchnia';
        public static $lazienka = '_lazienka';
        public static $przedpokoj = '_przedpokoj';
        public static $toaleta = '_toaleta';
        public static $pomieszczeniebiurowe = '_pomieszczeniebiurowe';
        public static $pomieszczeniesocjalne = '_pomieszczeniesocjalne';
        public static $pomieszczeniegospodarcze = '_pomieszczeniegospodarcze';
        public static $stajnia = '_stajnia';
        public static $stodola = '_stodola';
        public static $kurnik = '_kurnik';
        public static $owczarnia = '_owczarnia';
        public static $obora = '_obora';
        public static $chlewnia = '_chlewnia';
        public static $warsztat = '_warsztat';
        public static $garaz = '_garaz';
        public static $aktualna = '_aktualna';
        public static $zawieszona = '_zawieszona';
        public static $polska = '_polska';
        */
    }
?>